package workspace

import "errors"

var (
	ErrWorkspaceNotFound          = errors.New("workspace not found")
	ErrWorkspaceNameRequired      = errors.New("workspace name is required")
	ErrMemberNotFound             = errors.New("workspace member not found")
	ErrMemberAlreadyExists        = errors.New("user is already a member of this workspace")
	ErrInviteNotFound             = errors.New("invite not found")
	ErrInviteAlreadyExists        = errors.New("a pending invite already exists for this email")
	ErrInviteExpired              = errors.New("invite has expired")
	ErrInviteAlreadyProcessed     = errors.New("invite has already been processed")
	ErrInvalidRole                = errors.New("invalid workspace role")
	ErrInvalidResource            = errors.New("invalid resource")
	ErrInvalidAction              = errors.New("invalid action")
	ErrInvalidRingChannel         = errors.New("invalid ring channel")
	ErrCannotRemoveOwner          = errors.New("cannot remove the workspace owner")
	ErrCannotChangeOwnerRole      = errors.New("cannot change the owner role")
	ErrInsufficientPermissions    = errors.New("insufficient permissions for this action")
	ErrCannotModifySelf           = errors.New("cannot modify your own permissions")
	ErrPermissionAlreadyExists    = errors.New("permission already exists")
	ErrPermissionNotFound         = errors.New("permission not found")
	ErrCannotInviteSelf           = errors.New("cannot invite yourself")
	ErrDefaultWorkspace           = errors.New("cannot delete the default workspace")
	ErrUnauthorized               = errors.New("unauthorized access to this workspace")
	ErrResourceAssignmentNotFound = errors.New("resource assignment not found")
	ErrResourceAlreadyAssigned    = errors.New("resource is already assigned to this member")
	ErrResourceAccessDenied       = errors.New("access denied to this resource")
	ErrRoleNotFound               = errors.New("custom role not found")
	ErrRoleNameRequired           = errors.New("role name is required")
	ErrRoleInUse                  = errors.New("cannot delete role that is assigned to members")
	ErrInvalidDepartment          = errors.New("one or more department IDs do not belong to this workspace")
	ErrWorkspaceLimitReached      = errors.New("workspace limit reached: you cannot create more than 10 workspaces")
)
