package workspace

func need(r Resource, a Action) PermissionEntry {
	return PermissionEntry{Resource: r, Action: a}
}

var (
	conversationsRead = need(ResourceConversations, ActionRead)
	stagesRead        = need(ResourceStages, ActionRead)
	membersRead       = need(ResourceMembers, ActionRead)
)

var Features = []Feature{
	{
		Key:         "inbox",
		Name:        "Chat",
		Location:    "Menu lateral › Chat",
		Description: "Caixa de entrada com as conversas de todos os canais, com resposta, atribuição e contexto do contato.",
		Scopes:      []ScopeRule{ScopeDepartments, ScopeAssignedConversations},
		Capabilities: []Capability{
			{Key: "inbox.view", Description: "Ver a caixa de entrada e o histórico das conversas", Requires: []PermissionEntry{conversationsRead}, Screens: []Screen{ScreenLiveChat}},
			{Key: "inbox.view_others", Description: "Ver conversas atribuídas a outros membros da equipe", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionViewOthers)}},
			{Key: "inbox.reply", Description: "Responder, agendar mensagens e alterar o status das conversas", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionSend)}},
			{Key: "inbox.reopen", Description: "Reabrir conversas com a janela de atendimento encerrada", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionReopen)}},
			{Key: "inbox.assign", Description: "Passar conversas para outros membros da equipe", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionAssign), membersRead}},
			{Key: "inbox.delegate", Description: "Delegar uma conversa a um agente de IA ou a um fluxo específico, mesmo em canais sem automação ativa", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionDelegate), need(ResourceAgents, ActionRead), need(ResourceWorkflows, ActionRead)}},
			{Key: "inbox.automation", Description: "Ligar ou desligar a IA e as automações em uma conversa e gerenciar as visualizações salvas", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionUpdate)}},
			{Key: "inbox.roulette", Description: "Receber conversas pela roleta de atribuição automática", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionSend), need(ResourceConversations, ActionRoulette)}},
			{Key: "inbox.start_qr", Description: "Iniciar conversa com um número novo pelo WhatsApp conectado por QR Code", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppInstances, ActionSend)}},
			{Key: "inbox.start_official", Description: "Iniciar conversa com um número novo enviando um modelo pelo WhatsApp oficial", Requires: []PermissionEntry{need(ResourceWhatsAppTemplates, ActionSend), need(ResourceWhatsAppTemplates, ActionRead), need(ResourceBusinessPhones, ActionRead), conversationsRead}},
			{Key: "inbox.schedule_template", Description: "Agendar o envio de modelos oficiais em conversas do WhatsApp", Requires: []PermissionEntry{need(ResourceConversations, ActionSend), need(ResourceWhatsAppTemplates, ActionSend), need(ResourceWhatsAppTemplates, ActionRead), need(ResourceBusinessPhones, ActionRead), conversationsRead}},
			{Key: "inbox.labels", Description: "Aplicar e remover etiquetas nas conversas", Requires: []PermissionEntry{conversationsRead, need(ResourceLabels, ActionRead), need(ResourceLabels, ActionAssign)}},
			{Key: "inbox.stage", Description: "Definir a etapa do funil de uma conversa", Requires: []PermissionEntry{conversationsRead, stagesRead, need(ResourceStages, ActionAssign)}},
			{Key: "inbox.move_funnel", Description: "Mover conversas para outro funil", Requires: []PermissionEntry{conversationsRead, stagesRead, need(ResourceStages, ActionAssign), need(ResourceStages, ActionTransfer)}},
			{Key: "inbox.contact_edit", Description: "Renomear o contato e gerenciar as memórias da IA sobre ele", Requires: []PermissionEntry{conversationsRead, need(ResourceLeads, ActionUpdate)}},
			{Key: "inbox.contact_block", Description: "Bloquear um contato", Requires: []PermissionEntry{conversationsRead, need(ResourceLeads, ActionBlock)}},
			{Key: "inbox.analysis", Description: "Ver a análise da IA sobre cada conversa na lista e no Kanban", Requires: []PermissionEntry{conversationsRead, need(ResourceAudience, ActionRead)}},
			{Key: "inbox.ops_panel", Description: "Ver o painel de métricas operacionais dentro do Chat", Requires: []PermissionEntry{conversationsRead, need(ResourceAttendance, ActionRead)}},
		},
	},
	{
		Key:         "crm_board",
		Name:        "Kanban de conversas",
		Location:    "Menu lateral › Chat › visualização Kanban",
		Description: "Quadro com as conversas organizadas por etapa do funil, por responsável ou por etiqueta.",
		Scopes:      []ScopeRule{ScopeDepartments, ScopeAssignedConversations},
		Capabilities: []Capability{
			{Key: "crm_board.view", Description: "Ver o quadro Kanban com as conversas por etapa", Requires: []PermissionEntry{conversationsRead, stagesRead}},
			{Key: "crm_board.move_stage", Description: "Arrastar cartões entre etapas", Requires: []PermissionEntry{conversationsRead, stagesRead, need(ResourceStages, ActionAssign)}},
			{Key: "crm_board.move_funnel", Description: "Mover cartões para outro funil", Requires: []PermissionEntry{conversationsRead, stagesRead, need(ResourceStages, ActionAssign), need(ResourceStages, ActionTransfer)}},
			{Key: "crm_board.move_owner", Description: "Arrastar cartões entre responsáveis no quadro agrupado por responsável", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionAssign), membersRead}},
			{Key: "crm_board.move_label", Description: "Arrastar cartões entre etiquetas no quadro agrupado por etiqueta", Requires: []PermissionEntry{conversationsRead, need(ResourceLabels, ActionRead), need(ResourceLabels, ActionAssign)}},
			{Key: "crm_board.bulk", Description: "Aplicar ações em massa; cada ação exige também a permissão correspondente", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionUpdate)}},
		},
	},
	{
		Key:         "funnels",
		Name:        "Funis e etapas",
		Location:    "Menu lateral › Funis e etapas",
		Description: "Cadastro dos funis e das etapas usadas no Kanban, nas oportunidades e nas campanhas.",
		Capabilities: []Capability{
			{Key: "funnels.view", Description: "Ver os funis e as etapas", Requires: []PermissionEntry{stagesRead}, Screens: []Screen{ScreenFunnels}},
			{Key: "funnels.create", Description: "Criar funis e etapas", Requires: []PermissionEntry{stagesRead, need(ResourceStages, ActionCreate)}},
			{Key: "funnels.edit", Description: "Renomear, reordenar e duplicar funis e etapas e definir o funil padrão", Requires: []PermissionEntry{stagesRead, need(ResourceStages, ActionUpdate)}},
			{Key: "funnels.delete", Description: "Excluir funis e etapas", Requires: []PermissionEntry{stagesRead, need(ResourceStages, ActionDelete)}},
		},
	},
	{
		Key:         "stage_groups",
		Name:        "Grupos de etapas",
		Location:    "Página de grupos de etapas",
		Description: "Agrupamentos de etapas por departamento.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "stage_groups.view", Description: "Ver os grupos de etapas", Requires: []PermissionEntry{need(ResourceStageGroups, ActionRead)}, Screens: []Screen{ScreenStageGroups}},
			{Key: "stage_groups.create", Description: "Criar grupos de etapas", Requires: []PermissionEntry{need(ResourceStageGroups, ActionRead), need(ResourceStageGroups, ActionCreate)}},
			{Key: "stage_groups.edit", Description: "Editar grupos de etapas", Requires: []PermissionEntry{need(ResourceStageGroups, ActionRead), need(ResourceStageGroups, ActionUpdate)}},
			{Key: "stage_groups.delete", Description: "Excluir grupos de etapas", Requires: []PermissionEntry{need(ResourceStageGroups, ActionRead), need(ResourceStageGroups, ActionDelete)}},
		},
	},
	{
		Key:         "deals",
		Name:        "Oportunidades",
		Location:    "Menu lateral › Oportunidades",
		Description: "Quadro de oportunidades de venda por funil, com valores, responsáveis e conversas vinculadas.",
		Scopes:      []ScopeRule{ScopeDepartments, ScopeAssignedConversations},
		Capabilities: []Capability{
			{Key: "deals.view", Description: "Ver as oportunidades e o histórico delas", Requires: []PermissionEntry{conversationsRead, stagesRead}, Screens: []Screen{ScreenSales}},
			{Key: "deals.create", Description: "Criar e importar oportunidades, campos personalizados e visualizações salvas", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionCreate)}},
			{Key: "deals.edit", Description: "Editar, mover entre etapas e vincular oportunidades a conversas", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionUpdate)}},
			{Key: "deals.assign", Description: "Definir o responsável por uma oportunidade", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionAssign), membersRead}},
			{Key: "deals.delete", Description: "Excluir oportunidades, campos personalizados e visualizações salvas", ManagersOnly: true},
		},
	},
	{
		Key:         "labels",
		Name:        "Etiquetas",
		Location:    "Menu lateral › Chat › Gerenciar etiquetas",
		Description: "Etiquetas usadas para classificar as conversas.",
		Capabilities: []Capability{
			{Key: "labels.view", Description: "Ver as etiquetas", Requires: []PermissionEntry{need(ResourceLabels, ActionRead)}},
			{Key: "labels.create", Description: "Criar etiquetas", Requires: []PermissionEntry{need(ResourceLabels, ActionRead), need(ResourceLabels, ActionCreate)}},
			{Key: "labels.edit", Description: "Editar e reordenar etiquetas", Requires: []PermissionEntry{need(ResourceLabels, ActionRead), need(ResourceLabels, ActionUpdate)}},
			{Key: "labels.delete", Description: "Excluir etiquetas", Requires: []PermissionEntry{need(ResourceLabels, ActionRead), need(ResourceLabels, ActionDelete)}},
		},
	},
	{
		Key:         "message_shortcuts",
		Name:        "Atalhos de mensagem",
		Location:    "Menu lateral › Atalhos",
		Description: "Respostas prontas acionadas por atalho no campo de mensagem.",
		Capabilities: []Capability{
			{Key: "message_shortcuts.view", Description: "Ver e usar os atalhos de mensagem", Requires: []PermissionEntry{need(ResourceMessageShortcuts, ActionRead)}, Screens: []Screen{ScreenMessageShortcuts}},
			{Key: "message_shortcuts.create", Description: "Criar atalhos, inclusive direto do campo de mensagem", Requires: []PermissionEntry{need(ResourceMessageShortcuts, ActionRead), need(ResourceMessageShortcuts, ActionCreate)}},
			{Key: "message_shortcuts.edit", Description: "Editar atalhos", Requires: []PermissionEntry{need(ResourceMessageShortcuts, ActionRead), need(ResourceMessageShortcuts, ActionUpdate)}},
			{Key: "message_shortcuts.delete", Description: "Excluir atalhos", Requires: []PermissionEntry{need(ResourceMessageShortcuts, ActionRead), need(ResourceMessageShortcuts, ActionDelete)}},
		},
	},
	{
		Key:         "media",
		Name:        "Arquivos de mídia",
		Location:    "Anexos nas conversas, campanhas e modelos",
		Description: "Imagens, áudios e documentos enviados pelo workspace.",
		Capabilities: []Capability{
			{Key: "media.view", Description: "Ver e baixar arquivos de mídia", Requires: []PermissionEntry{need(ResourceMedia, ActionRead)}},
			{Key: "media.upload", Description: "Enviar arquivos de mídia e gerar imagens com IA", Requires: []PermissionEntry{need(ResourceMedia, ActionCreate)}},
		},
	},
	{
		Key:         "leads",
		Name:        "Leads",
		Location:    "Menu lateral › Leads",
		Description: "Base de contatos com histórico de campanhas e conversas.",
		Capabilities: []Capability{
			{Key: "leads.view", Description: "Ver os leads e o histórico de campanhas e conversas de cada um", Requires: []PermissionEntry{need(ResourceLeads, ActionRead)}, Screens: []Screen{ScreenLeads, ScreenLeadDetail}},
			{Key: "leads.import", Description: "Cadastrar e importar leads", Requires: []PermissionEntry{need(ResourceLeads, ActionRead), need(ResourceLeads, ActionCreate)}},
			{Key: "leads.import_to_inbox", Description: "Criar conversas na caixa de entrada ao importar leads", Requires: []PermissionEntry{need(ResourceLeads, ActionRead), need(ResourceLeads, ActionCreate), need(ResourceUnofficialWhatsAppInstances, ActionSend)}},
			{Key: "leads.edit", Description: "Renomear leads e gerenciar as memórias da IA", Requires: []PermissionEntry{need(ResourceLeads, ActionRead), need(ResourceLeads, ActionUpdate)}},
			{Key: "leads.block", Description: "Bloquear leads", Requires: []PermissionEntry{need(ResourceLeads, ActionRead), need(ResourceLeads, ActionBlock)}},
		},
	},
	{
		Key:         "calls",
		Name:        "Chamadas de WhatsApp",
		Location:    "Menu lateral › Chat › botão de chamada da conversa",
		Description: "Ligações de voz pelo WhatsApp feitas e atendidas dentro das conversas.",
		Capabilities: []Capability{
			{Key: "calls.use", Description: "Fazer e atender chamadas de WhatsApp", Requires: []PermissionEntry{need(ResourceCallSession, ActionUse)}},
			{Key: "calls.request_permission", Description: "Pedir ao cliente permissão para receber ligações", Requires: []PermissionEntry{conversationsRead, need(ResourceConversations, ActionCall), need(ResourceCallSession, ActionUse)}},
			{Key: "calls.presence", Description: "Ver quais membros estão conectados às chamadas em tempo real", Requires: []PermissionEntry{need(ResourceCallSession, ActionUse), need(ResourceCallSession, ActionListMembers)}},
		},
	},
	{
		Key:         "call_history",
		Name:        "Histórico de chamadas",
		Location:    "Menu lateral › Telefonia › Histórico",
		Description: "Registro das ligações pela linha telefônica e pelo WhatsApp: quem ligou, quem atendeu, transferências, resultado, duração, custo e gravação.",
		Capabilities: []Capability{
			{Key: "call_history.view", Description: "Ver as chamadas de que participou, com a linha do tempo de cada uma", Requires: []PermissionEntry{need(ResourceCallHistory, ActionRead)}, Screens: []Screen{ScreenCallHistory}},
			{Key: "call_history.view_team", Description: "Ver as chamadas de todos os membros do workspace", Requires: []PermissionEntry{need(ResourceCallHistory, ActionRead), need(ResourceCallHistory, ActionViewOthers)}},
			{Key: "call_history.listen", Description: "Ouvir e baixar as gravações das chamadas", Requires: []PermissionEntry{need(ResourceCallHistory, ActionRead), need(ResourceCallRecordings, ActionRead)}},
		},
	},
	{
		Key:         "attendance",
		Name:        "Métricas de atendimento",
		Location:    "Menu lateral › Métricas › Atendimento",
		Description: "Indicadores de atendimento: volume, tempos, filas, ocupação, equipe e metas.",
		Capabilities: []Capability{
			{Key: "attendance.view", Description: "Ver as métricas de atendimento", Requires: []PermissionEntry{need(ResourceAttendance, ActionRead)}, Screens: []Screen{ScreenAttendance}},
			{Key: "attendance.targets_view", Description: "Ver as metas de atendimento", Requires: []PermissionEntry{need(ResourceAttendance, ActionRead), need(ResourceAttendanceTargets, ActionRead)}},
			{Key: "attendance.targets_edit", Description: "Definir as metas de atendimento", Requires: []PermissionEntry{need(ResourceAttendance, ActionRead), need(ResourceAttendanceTargets, ActionUpdate)}},
			{Key: "attendance.targets_delete", Description: "Remover metas de atendimento", Requires: []PermissionEntry{need(ResourceAttendance, ActionRead), need(ResourceAttendanceTargets, ActionDelete)}},
			{Key: "attendance.campaign_report", Description: "Ver o relatório de disparos das campanhas", Requires: []PermissionEntry{need(ResourceAttendance, ActionRead), need(ResourceWhatsAppCampaigns, ActionRead)}},
		},
	},
	{
		Key:         "reports",
		Name:        "Relatórios",
		Location:    "Menu lateral › Métricas › Relatórios",
		Description: "Relatórios gerados sob demanda para download.",
		Capabilities: []Capability{
			{Key: "reports.view", Description: "Ver e baixar relatórios", Requires: []PermissionEntry{need(ResourceReports, ActionRead)}, Screens: []Screen{ScreenReports}},
			{Key: "reports.create", Description: "Solicitar a geração de relatórios", Requires: []PermissionEntry{need(ResourceReports, ActionRead), need(ResourceReports, ActionCreate)}},
		},
	},
	{
		Key:         "audience",
		Name:        "Audiência",
		Location:    "Menu lateral › Métricas › Audiência",
		Description: "Análise por IA de comentários e conversas: temas, assuntos, autores e alertas.",
		Capabilities: []Capability{
			{Key: "audience.view", Description: "Ver a análise de comentários e conversas", Requires: []PermissionEntry{need(ResourceAudience, ActionRead)}, Screens: []Screen{ScreenAudience}},
			{Key: "audience.configure", Description: "Configurar a análise, moderar autores e iniciar reprocessamentos", Requires: []PermissionEntry{need(ResourceAudience, ActionRead), need(ResourceAudience, ActionUpdate)}},
			{Key: "audience.alerts", Description: "Responder e encaminhar comentários e configurar alertas por WhatsApp", Requires: []PermissionEntry{need(ResourceAudience, ActionRead), need(ResourceAudience, ActionSend), need(ResourceConversations, ActionSend)}, Screens: []Screen{ScreenAnalysisAlerts}},
		},
	},
	{
		Key:         "ai_chat",
		Name:        "Elo",
		Location:    "Menu lateral › Elo",
		Description: "Assistente de IA do workspace.",
		Capabilities: []Capability{
			{Key: "ai_chat.view", Description: "Abrir o Elo e ver as conversas anteriores", Requires: []PermissionEntry{need(ResourceAIChat, ActionRead)}, Screens: []Screen{ScreenAIChat}},
			{Key: "ai_chat.chat", Description: "Conversar com o Elo", Requires: []PermissionEntry{need(ResourceAIChat, ActionRead), need(ResourceAIChat, ActionCreate)}},
			{Key: "ai_chat.manage", Description: "Renomear conversas e aprovar ou recusar as ações propostas pelo Elo", Requires: []PermissionEntry{need(ResourceAIChat, ActionRead), need(ResourceAIChat, ActionUpdate)}},
			{Key: "ai_chat.delete", Description: "Excluir conversas com o Elo", Requires: []PermissionEntry{need(ResourceAIChat, ActionRead), need(ResourceAIChat, ActionDelete)}},
		},
	},
	{
		Key:         "agents",
		Name:        "Agentes",
		Location:    "Menu lateral › Agentes",
		Description: "Agentes de IA que atendem as conversas.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "agents.view", Description: "Ver a lista de agentes", Requires: []PermissionEntry{need(ResourceAgents, ActionRead)}, Screens: []Screen{ScreenAgents, ScreenAgentsArchived}},
			{Key: "agents.details", Description: "Abrir as configurações completas de um agente", Requires: []PermissionEntry{need(ResourceAgents, ActionRead), need(ResourceAgents, ActionReadDetails)}, Screens: []Screen{ScreenAgentDetail}},
			{Key: "agents.create", Description: "Criar agentes", Requires: []PermissionEntry{need(ResourceAgents, ActionRead), need(ResourceAgents, ActionCreate)}, Screens: []Screen{ScreenAgentNew}},
			{Key: "agents.edit", Description: "Editar, simular, arquivar, vincular bases de conhecimento e mudar o departamento de agentes", Requires: []PermissionEntry{need(ResourceAgents, ActionRead), need(ResourceAgents, ActionUpdate)}, Screens: []Screen{ScreenAgentEdit, ScreenAgentSimulator}},
			{Key: "agents.delete", Description: "Excluir agentes", Requires: []PermissionEntry{need(ResourceAgents, ActionRead), need(ResourceAgents, ActionDelete)}},
		},
	},
	{
		Key:         "mcp",
		Name:        "Servidores MCP",
		Location:    "Menu lateral › Agentes › Servidores MCP",
		Description: "Integrações externas disponíveis para os agentes.",
		Capabilities: []Capability{
			{Key: "mcp.view", Description: "Ver os servidores MCP", Requires: []PermissionEntry{need(ResourceMCP, ActionRead)}, Screens: []Screen{ScreenMCPServers}},
			{Key: "mcp.create", Description: "Habilitar servidores integrados e registrar servidores remotos", Requires: []PermissionEntry{need(ResourceMCP, ActionRead), need(ResourceMCP, ActionCreate)}},
			{Key: "mcp.configure", Description: "Configurar as credenciais dos servidores", Requires: []PermissionEntry{need(ResourceMCP, ActionRead), need(ResourceMCP, ActionUpdate)}},
			{Key: "mcp.delete", Description: "Remover servidores", Requires: []PermissionEntry{need(ResourceMCP, ActionRead), need(ResourceMCP, ActionDelete)}},
		},
	},
	{
		Key:         "knowledge_bases",
		Name:        "Bases de conhecimento",
		Location:    "Menu lateral › Conhecimento",
		Description: "Documentos que os agentes e o Elo consultam para responder.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "knowledge_bases.view", Description: "Ver as bases e os documentos", Requires: []PermissionEntry{need(ResourceKnowledgeBases, ActionRead)}, Screens: []Screen{ScreenKnowledgeBases, ScreenKnowledgeBaseDetail}},
			{Key: "knowledge_bases.create", Description: "Criar bases e adicionar documentos", Requires: []PermissionEntry{need(ResourceKnowledgeBases, ActionRead), need(ResourceKnowledgeBases, ActionCreate)}, Screens: []Screen{ScreenKnowledgeBaseNew}},
			{Key: "knowledge_bases.edit", Description: "Editar bases", Requires: []PermissionEntry{need(ResourceKnowledgeBases, ActionRead), need(ResourceKnowledgeBases, ActionUpdate)}, Screens: []Screen{ScreenKnowledgeBaseEdit}},
			{Key: "knowledge_bases.delete", Description: "Excluir bases e documentos", Requires: []PermissionEntry{need(ResourceKnowledgeBases, ActionRead), need(ResourceKnowledgeBases, ActionDelete)}},
		},
	},
	{
		Key:         "workflows",
		Name:        "Automações",
		Location:    "Menu lateral › Automações",
		Description: "Fluxos de automação que reagem a eventos das conversas.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "workflows.view", Description: "Ver as automações, as configurações e as execuções", Requires: []PermissionEntry{need(ResourceWorkflows, ActionRead)}, Screens: []Screen{ScreenWorkflows, ScreenWorkflowDetail}},
			{Key: "workflows.create", Description: "Criar, importar e executar automações manualmente", Requires: []PermissionEntry{need(ResourceWorkflows, ActionRead), need(ResourceWorkflows, ActionCreate)}, Screens: []Screen{ScreenWorkflowNew}},
			{Key: "workflows.edit", Description: "Editar, ativar, pausar, testar e configurar webhooks de automações", Requires: []PermissionEntry{need(ResourceWorkflows, ActionRead), need(ResourceWorkflows, ActionUpdate)}},
			{Key: "workflows.delete", Description: "Excluir automações", Requires: []PermissionEntry{need(ResourceWorkflows, ActionRead), need(ResourceWorkflows, ActionDelete)}},
		},
	},
	{
		Key:         "whatsapp_campaigns",
		Name:        "Disparos do WhatsApp oficial",
		Location:    "Menu lateral › WhatsApp › Disparos e Receptivas",
		Description: "Campanhas de envio pelo WhatsApp oficial, ativas e receptivas.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "whatsapp_campaigns.view", Description: "Ver as campanhas, os contatos e os resultados", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead)}, Screens: []Screen{ScreenWhatsAppCampaigns, ScreenWhatsAppCampaignsArchived, ScreenWhatsAppCampaignDetail}},
			{Key: "whatsapp_campaigns.crm", Description: "Abrir as conversas de uma campanha", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead), conversationsRead}, Screens: []Screen{ScreenWhatsAppCampaignCRM}},
			{Key: "whatsapp_campaigns.create", Description: "Criar campanhas e importar contatos", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead), need(ResourceWhatsAppCampaigns, ActionCreate)}, Screens: []Screen{ScreenWhatsAppCampaignNew}},
			{Key: "whatsapp_campaigns.edit", Description: "Editar campanhas e contatos, reiniciar, limpar o histórico e arquivar", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead), need(ResourceWhatsAppCampaigns, ActionUpdate)}, Screens: []Screen{ScreenWhatsAppCampaignEdit}},
			{Key: "whatsapp_campaigns.delete", Description: "Excluir campanhas e contatos", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead), need(ResourceWhatsAppCampaigns, ActionDelete)}},
			{Key: "whatsapp_campaigns.start", Description: "Iniciar envios e envios rápidos", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead), need(ResourceWhatsAppCampaigns, ActionStart)}},
			{Key: "whatsapp_campaigns.stop", Description: "Pausar e parar envios e ligar ou desligar a IA de um contato", Requires: []PermissionEntry{need(ResourceWhatsAppCampaigns, ActionRead), need(ResourceWhatsAppCampaigns, ActionStop)}},
		},
	},
	{
		Key:         "whatsapp_templates",
		Name:        "Templates",
		Location:    "Menu lateral › WhatsApp › Templates",
		Description: "Modelos de mensagem aprovados pela Meta para o WhatsApp oficial.",
		Capabilities: []Capability{
			{Key: "whatsapp_templates.view", Description: "Ver os modelos e o status de aprovação", Requires: []PermissionEntry{need(ResourceWhatsAppTemplates, ActionRead)}, Screens: []Screen{ScreenWhatsAppTemplates, ScreenWhatsAppTemplateDetail}},
			{Key: "whatsapp_templates.create", Description: "Criar modelos e enviá-los para aprovação", Requires: []PermissionEntry{need(ResourceWhatsAppTemplates, ActionRead), need(ResourceWhatsAppTemplates, ActionCreate)}, Screens: []Screen{ScreenWhatsAppTemplateNew}},
			{Key: "whatsapp_templates.edit", Description: "Sincronizar modelos com a Meta e trocar a mídia do cabeçalho", Requires: []PermissionEntry{need(ResourceWhatsAppTemplates, ActionRead), need(ResourceWhatsAppTemplates, ActionUpdate)}},
			{Key: "whatsapp_templates.delete", Description: "Excluir modelos", Requires: []PermissionEntry{need(ResourceWhatsAppTemplates, ActionRead), need(ResourceWhatsAppTemplates, ActionDelete)}},
			{Key: "whatsapp_templates.send", Description: "Enviar um modelo para um número novo", Requires: []PermissionEntry{need(ResourceWhatsAppTemplates, ActionSend), need(ResourceWhatsAppTemplates, ActionRead), need(ResourceBusinessPhones, ActionRead), conversationsRead}, Screens: []Screen{ScreenWhatsAppTemplateSend}},
		},
	},
	{
		Key:         "business_phones",
		Name:        "Telefones do WhatsApp oficial",
		Location:    "Menu lateral › WhatsApp › Telefones",
		Description: "Números conectados à API oficial do WhatsApp.",
		Capabilities: []Capability{
			{Key: "business_phones.view", Description: "Ver os números, o perfil e o status de chamadas", Requires: []PermissionEntry{need(ResourceBusinessPhones, ActionRead)}, Screens: []Screen{ScreenBusinessPhones, ScreenBusinessPhoneDetail, ScreenBusinessPhoneGuide}},
			{Key: "business_phones.connect", Description: "Conectar números ao WhatsApp oficial", ManagersOnly: true, Screens: []Screen{ScreenBusinessPhoneConnect}},
			{Key: "business_phones.manage", Description: "Sincronizar, verificar, editar o perfil, ativar chamadas e desconectar números", ManagersOnly: true},
		},
	},
	{
		Key:         "unofficial_numbers",
		Name:        "Números por QR Code",
		Location:    "Menu lateral › WhatsApp › Números",
		Description: "Números de WhatsApp conectados por QR Code.",
		Capabilities: []Capability{
			{Key: "unofficial_numbers.view", Description: "Ver os números, a conexão e os grupos", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppInstances, ActionRead)}, Screens: []Screen{ScreenUnofficialNumbers, ScreenUnofficialNumberDetail}},
			{Key: "unofficial_numbers.connect", Description: "Conectar números por QR Code", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppInstances, ActionRead), need(ResourceUnofficialWhatsAppInstances, ActionCreate)}, Screens: []Screen{ScreenUnofficialNumberConnect}},
			{Key: "unofficial_numbers.edit", Description: "Editar, reconectar e reiniciar números e gerenciar grupos", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppInstances, ActionRead), need(ResourceUnofficialWhatsAppInstances, ActionUpdate)}},
			{Key: "unofficial_numbers.delete", Description: "Desconectar números, sair de grupos e remover participantes", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppInstances, ActionRead), need(ResourceUnofficialWhatsAppInstances, ActionDelete)}},
		},
	},
	{
		Key:         "unofficial_campaigns",
		Name:        "Disparos por QR Code",
		Location:    "Menu lateral › WhatsApp › Disparos por QR Code",
		Description: "Campanhas de envio pelos números conectados por QR Code.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "unofficial_campaigns.view", Description: "Ver as campanhas, os contatos e os resultados", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppCampaigns, ActionRead)}, Screens: []Screen{ScreenUnofficialCampaigns, ScreenUnofficialCampaignsArch, ScreenUnofficialCampaignDetail}},
			{Key: "unofficial_campaigns.create", Description: "Criar campanhas e importar contatos", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppCampaigns, ActionRead), need(ResourceUnofficialWhatsAppCampaigns, ActionCreate)}, Screens: []Screen{ScreenUnofficialCampaignNew}},
			{Key: "unofficial_campaigns.edit", Description: "Editar, validar, reiniciar, limpar o histórico e arquivar campanhas", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppCampaigns, ActionRead), need(ResourceUnofficialWhatsAppCampaigns, ActionUpdate)}, Screens: []Screen{ScreenUnofficialCampaignEdit}},
			{Key: "unofficial_campaigns.delete", Description: "Excluir campanhas e contatos", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppCampaigns, ActionRead), need(ResourceUnofficialWhatsAppCampaigns, ActionDelete)}},
			{Key: "unofficial_campaigns.start", Description: "Iniciar disparos", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppCampaigns, ActionRead), need(ResourceUnofficialWhatsAppCampaigns, ActionStart)}},
			{Key: "unofficial_campaigns.stop", Description: "Pausar e parar disparos", Requires: []PermissionEntry{need(ResourceUnofficialWhatsAppCampaigns, ActionRead), need(ResourceUnofficialWhatsAppCampaigns, ActionStop)}},
		},
	},
	{
		Key:         "instagram",
		Name:        "Instagram",
		Location:    "Menu lateral › Instagram › Contas",
		Description: "Contas do Instagram conectadas, com publicações, comentários e regras de resposta.",
		Capabilities: []Capability{
			{Key: "instagram.view", Description: "Ver as contas, as publicações e os comentários", Requires: []PermissionEntry{need(ResourceInstagramAccounts, ActionRead)}, Screens: []Screen{ScreenInstagramAccounts, ScreenInstagramAccount}},
			{Key: "instagram.connect", Description: "Conectar e reconectar contas", Requires: []PermissionEntry{need(ResourceInstagramAccounts, ActionRead), need(ResourceInstagramAccounts, ActionCreate)}, Screens: []Screen{ScreenInstagramConnect}},
			{Key: "instagram.manage", Description: "Publicar, responder e moderar comentários e editar as regras e configurações", Requires: []PermissionEntry{need(ResourceInstagramAccounts, ActionRead), need(ResourceInstagramAccounts, ActionUpdate)}},
			{Key: "instagram.disconnect", Description: "Desconectar contas", Requires: []PermissionEntry{need(ResourceInstagramAccounts, ActionRead), need(ResourceInstagramAccounts, ActionDelete)}},
		},
	},
	{
		Key:         "facebook",
		Name:        "Facebook",
		Location:    "Menu lateral › Facebook › Páginas",
		Description: "Páginas do Facebook conectadas, com publicações e comentários.",
		Capabilities: []Capability{
			{Key: "facebook.view", Description: "Ver as páginas, as publicações e os comentários", Requires: []PermissionEntry{need(ResourceFacebookPages, ActionRead)}, Screens: []Screen{ScreenFacebookPages}},
			{Key: "facebook.connect", Description: "Conectar páginas", Requires: []PermissionEntry{need(ResourceFacebookPages, ActionRead), need(ResourceFacebookPages, ActionCreate)}, Screens: []Screen{ScreenFacebookConnect}},
			{Key: "facebook.manage", Description: "Publicar, moderar comentários e editar as configurações das páginas", Requires: []PermissionEntry{need(ResourceFacebookPages, ActionRead), need(ResourceFacebookPages, ActionUpdate)}},
			{Key: "facebook.disconnect", Description: "Desconectar páginas", Requires: []PermissionEntry{need(ResourceFacebookPages, ActionRead), need(ResourceFacebookPages, ActionDelete)}},
		},
	},
	{
		Key:         "ads",
		Name:        "Anúncios da Meta",
		Location:    "Menu lateral › Meta",
		Description: "Gerenciador de anúncios da Meta (Facebook e Instagram): campanhas, conjuntos e anúncios com resultados, detalhamentos e custo por lead; criação e edição de anúncios de todos os objetivos; públicos, formulários de cadastro e seus leads, regras automáticas, testes A/B, pixels e envio de conversões do CRM.",
		Capabilities: []Capability{
			{Key: "ads.view", Description: "Ver a visão geral da conta com o que falta para veicular, as campanhas, os resultados, os públicos, os formulários com seus leads, as regras, as conversões e as Páginas com o WhatsApp, o Instagram e os termos de cadastro de cada uma", Requires: []PermissionEntry{need(ResourceAds, ActionRead)}, Screens: []Screen{ScreenAdsOverview, ScreenAdsManager, ScreenAdsEditor, ScreenAdsReports, ScreenAdsAudiences, ScreenAdsForms, ScreenAdsRules, ScreenAdsConversions, ScreenAdsPages}},
			{Key: "ads.create", Description: "Conectar contas de anúncios e criar anúncios", Requires: []PermissionEntry{need(ResourceAds, ActionRead), need(ResourceAds, ActionCreate)}, Screens: []Screen{ScreenAdsCreate}},
			{Key: "ads.toggle", Description: "Ligar e desligar campanhas, conjuntos e anúncios", Requires: []PermissionEntry{need(ResourceAds, ActionRead), need(ResourceAds, ActionStart), need(ResourceAds, ActionStop)}},
			{Key: "ads.edit", Description: "Editar campanhas, conjuntos e anúncios, orçamentos, limite de gasto da conta, regras e envio de conversões, e arquivar", Requires: []PermissionEntry{need(ResourceAds, ActionRead), need(ResourceAds, ActionUpdate)}},
			{Key: "ads.disconnect", Description: "Desconectar contas de anúncios", Requires: []PermissionEntry{need(ResourceAds, ActionRead), need(ResourceAds, ActionDelete)}},
		},
	},
	{
		Key:         "sip_trunks",
		Name:        "Linhas telefônicas",
		Location:    "Menu lateral › Telefonia › Linhas telefônicas, e o discador na borda direita",
		Description: "Linhas telefônicas da operadora, conectadas por SIP, e o discador que faz e atende ligações por elas.",
		Capabilities: []Capability{
			{Key: "sip_trunks.view", Description: "Ver as linhas, se estão conectadas à operadora e as ligações em andamento", Requires: []PermissionEntry{need(ResourceSIPTrunks, ActionRead)}, Screens: []Screen{ScreenSIPTrunks}},
			{Key: "sip_trunks.connect", Description: "Conectar linhas", Requires: []PermissionEntry{need(ResourceSIPTrunks, ActionRead), need(ResourceSIPTrunks, ActionCreate)}},
			{Key: "sip_trunks.edit", Description: "Editar linhas e suas credenciais", Requires: []PermissionEntry{need(ResourceSIPTrunks, ActionRead), need(ResourceSIPTrunks, ActionUpdate)}},
			{Key: "sip_trunks.remove", Description: "Remover linhas, encerrando as ligações em andamento", Requires: []PermissionEntry{need(ResourceSIPTrunks, ActionRead), need(ResourceSIPTrunks, ActionDelete)}},
			{Key: "sip_trunks.call", Description: "Fazer e atender ligações pelo discador", Requires: []PermissionEntry{need(ResourceSIPTrunks, ActionRead), need(ResourceSIPTrunks, ActionCall), need(ResourceCallSession, ActionUse)}},
		},
	},
	{
		Key:         "call_queues",
		Name:        "Filas de atendimento",
		Location:    "Menu lateral › Telefonia › Filas",
		Description: "Filas que distribuem ligações entre quem está livre, com música de espera, e as transferências entre colegas e filas.",
		Capabilities: []Capability{
			{Key: "call_queues.view", Description: "Ver as filas, quem atende cada uma e a música de espera", Requires: []PermissionEntry{need(ResourceCallQueues, ActionRead)}, Screens: []Screen{ScreenCallQueues}},
			{Key: "call_queues.create", Description: "Criar filas", Requires: []PermissionEntry{need(ResourceCallQueues, ActionRead), need(ResourceCallQueues, ActionCreate)}},
			{Key: "call_queues.edit", Description: "Editar filas e a música de espera do workspace", Requires: []PermissionEntry{need(ResourceCallQueues, ActionRead), need(ResourceCallQueues, ActionUpdate)}},
			{Key: "call_queues.remove", Description: "Remover filas", Requires: []PermissionEntry{need(ResourceCallQueues, ActionRead), need(ResourceCallQueues, ActionDelete)}},
			{Key: "call_queues.transfer", Description: "Transferir uma ligação em andamento (linha telefônica ou WhatsApp) para um colega ou uma fila; quem recebe precisa poder atender aquele tipo de ligação", Requires: []PermissionEntry{need(ResourceCallSession, ActionUse), need(ResourceCallSession, ActionListMembers), need(ResourceCallSession, ActionTransfer)}},
		},
	},
	{
		Key:         "telegram",
		Name:        "Telegram",
		Location:    "Menu lateral › Telegram › Contas",
		Description: "Bots do Telegram conectados e seus links de atribuição.",
		Capabilities: []Capability{
			{Key: "telegram.view", Description: "Ver os bots e os links de atribuição", Requires: []PermissionEntry{need(ResourceTelegramAccounts, ActionRead)}, Screens: []Screen{ScreenTelegramAccounts, ScreenTelegramAccount}},
			{Key: "telegram.connect", Description: "Conectar bots", Requires: []PermissionEntry{need(ResourceTelegramAccounts, ActionRead), need(ResourceTelegramAccounts, ActionCreate)}, Screens: []Screen{ScreenTelegramConnect}},
			{Key: "telegram.edit", Description: "Editar bots, registrar o webhook novamente e gerenciar links", Requires: []PermissionEntry{need(ResourceTelegramAccounts, ActionRead), need(ResourceTelegramAccounts, ActionUpdate)}},
			{Key: "telegram.disconnect", Description: "Desconectar bots", Requires: []PermissionEntry{need(ResourceTelegramAccounts, ActionRead), need(ResourceTelegramAccounts, ActionDelete)}},
		},
	},
	{
		Key:         "webchat",
		Name:        "WebChat",
		Location:    "Menu lateral › WebChat",
		Description: "WebChats instalados nos sites da empresa: sites permitidos, formulário inicial, aparência, verificação de identidade e o agente ou fluxo que atende.",
		Capabilities: []Capability{
			{Key: "webchat.view", Description: "Ver os WebChats e o código de instalação", Requires: []PermissionEntry{need(ResourceWebchatWidgets, ActionRead)}, Screens: []Screen{ScreenWebchatWidgets, ScreenWebchatWidget}},
			{Key: "webchat.create", Description: "Criar WebChats", Requires: []PermissionEntry{need(ResourceWebchatWidgets, ActionRead), need(ResourceWebchatWidgets, ActionCreate)}, Screens: []Screen{ScreenWebchatNew}},
			{Key: "webchat.edit", Description: "Editar sites permitidos, formulário, aparência, identidade e automação", Requires: []PermissionEntry{need(ResourceWebchatWidgets, ActionRead), need(ResourceWebchatWidgets, ActionUpdate)}},
			{Key: "webchat.remove", Description: "Remover WebChats", Requires: []PermissionEntry{need(ResourceWebchatWidgets, ActionRead), need(ResourceWebchatWidgets, ActionDelete)}},
		},
	},
	{
		Key:         "links",
		Name:        "Links",
		Location:    "Menu lateral › Links",
		Description: "Links curtos com QR Code e métricas de acesso.",
		Capabilities: []Capability{
			{Key: "links.view", Description: "Ver os links e as métricas de acesso", Requires: []PermissionEntry{need(ResourceShortLinks, ActionRead)}, Screens: []Screen{ScreenLinks, ScreenLinkDetail}},
			{Key: "links.create", Description: "Criar links", Requires: []PermissionEntry{need(ResourceShortLinks, ActionRead), need(ResourceShortLinks, ActionCreate)}, Screens: []Screen{ScreenLinkNew}},
			{Key: "links.edit", Description: "Editar links", Requires: []PermissionEntry{need(ResourceShortLinks, ActionRead), need(ResourceShortLinks, ActionUpdate)}, Screens: []Screen{ScreenLinkEdit}},
			{Key: "links.delete", Description: "Excluir links", Requires: []PermissionEntry{need(ResourceShortLinks, ActionRead), need(ResourceShortLinks, ActionDelete)}},
		},
	},
	{
		Key:         "calendar",
		Name:        "Calendário",
		Location:    "Menu lateral › Calendário",
		Description: "Eventos do workspace e integração com o Google Agenda.",
		Capabilities: []Capability{
			{Key: "calendar.view", Description: "Ver os eventos e o status da integração com o Google Agenda", Requires: []PermissionEntry{need(ResourceCalendar, ActionRead)}, Screens: []Screen{ScreenCalendar, ScreenCalendarSettings, ScreenIntegrations}},
			{Key: "calendar.create", Description: "Criar eventos e conectar o Google Agenda", Requires: []PermissionEntry{need(ResourceCalendar, ActionRead), need(ResourceCalendar, ActionCreate)}},
			{Key: "calendar.edit", Description: "Editar eventos", Requires: []PermissionEntry{need(ResourceCalendar, ActionRead), need(ResourceCalendar, ActionUpdate)}},
			{Key: "calendar.delete", Description: "Excluir eventos e desconectar o Google Agenda", Requires: []PermissionEntry{need(ResourceCalendar, ActionRead), need(ResourceCalendar, ActionDelete)}},
		},
	},
	{
		Key:         "issues",
		Name:        "Suporte",
		Location:    "Menu lateral › Suporte",
		Description: "Solicitações de suporte abertas com a equipe Vozko.",
		Capabilities: []Capability{
			{Key: "issues.view", Description: "Ver as solicitações e as respostas", Requires: []PermissionEntry{need(ResourceIssues, ActionRead)}, Screens: []Screen{ScreenIssues, ScreenIssueDetail}},
			{Key: "issues.create", Description: "Abrir solicitações", Requires: []PermissionEntry{need(ResourceIssues, ActionRead), need(ResourceIssues, ActionCreate)}, Screens: []Screen{ScreenIssueNew}},
			{Key: "issues.respond", Description: "Responder e encerrar solicitações", Requires: []PermissionEntry{need(ResourceIssues, ActionRead), need(ResourceIssues, ActionUpdate)}},
		},
	},
	{
		Key:         "billing",
		Name:        "Plano e saldo",
		Location:    "Menu lateral › Planos, Addons, Saldo e Faturas",
		Description: "Assinatura, complementos, saldo e faturas do workspace.",
		Capabilities: []Capability{
			{Key: "billing.balance", Description: "Ver o saldo, as transações e as faturas", Requires: []PermissionEntry{need(ResourceBalance, ActionRead)}, Screens: []Screen{ScreenBalance, ScreenInvoices}},
			{Key: "billing.plans", Description: "Ver os planos, os complementos e a assinatura atual", Requires: []PermissionEntry{need(ResourcePlans, ActionRead)}, Screens: []Screen{ScreenPlans, ScreenAddons}},
			{Key: "billing.purchase", Description: "Contratar planos e complementos e gerar faturas de recarga", Requires: []PermissionEntry{need(ResourcePlans, ActionRead), need(ResourcePlans, ActionCreate)}},
			{Key: "billing.cancel", Description: "Cancelar a assinatura e complementos", Requires: []PermissionEntry{need(ResourcePlans, ActionRead), need(ResourcePlans, ActionDelete)}},
		},
	},
	{
		Key:         "team",
		Name:        "Equipe",
		Location:    "Menu lateral › Workspace",
		Description: "Membros, convites e permissões do workspace.",
		Scopes:      []ScopeRule{ScopeDepartments},
		Capabilities: []Capability{
			{Key: "team.workspace", Description: "Abrir as configurações do workspace e os próprios convites", Screens: []Screen{ScreenWorkspace, ScreenWorkspaceInvites}},
			{Key: "team.members", Description: "Ver os membros, as funções e as permissões de cada um", Requires: []PermissionEntry{membersRead}},
			{Key: "team.members_other_departments", Description: "Ver membros de outros departamentos", Requires: []PermissionEntry{membersRead, need(ResourceMembers, ActionViewOthers)}},
			{Key: "team.invite", Description: "Convidar membros", Requires: []PermissionEntry{membersRead, need(ResourceMembers, ActionCreate)}},
			{Key: "team.edit", Description: "Alterar a função e as permissões de membros", Requires: []PermissionEntry{membersRead, need(ResourceMembers, ActionUpdate)}},
			{Key: "team.remove", Description: "Remover membros e cancelar convites", Requires: []PermissionEntry{membersRead, need(ResourceMembers, ActionDelete)}},
		},
	},
	{
		Key:         "roles",
		Name:        "Funções",
		Location:    "Menu lateral › Workspace › Funções",
		Description: "Funções personalizadas com conjuntos de permissões.",
		Capabilities: []Capability{
			{Key: "roles.view", Description: "Ver as funções e as permissões de cada uma", Requires: []PermissionEntry{need(ResourceRoles, ActionRead)}},
			{Key: "roles.create", Description: "Criar funções", Requires: []PermissionEntry{need(ResourceRoles, ActionRead), need(ResourceRoles, ActionCreate)}},
			{Key: "roles.edit", Description: "Editar funções e as permissões delas", Requires: []PermissionEntry{need(ResourceRoles, ActionRead), need(ResourceRoles, ActionUpdate)}},
			{Key: "roles.delete", Description: "Excluir funções", Requires: []PermissionEntry{need(ResourceRoles, ActionRead), need(ResourceRoles, ActionDelete)}},
		},
	},
	{
		Key:         "departments",
		Name:        "Departamentos",
		Location:    "Menu lateral › Workspace › Departamentos",
		Description: "Departamentos que limitam quais conversas, agentes e campanhas cada membro vê.",
		Capabilities: []Capability{
			{Key: "departments.view", Description: "Ver os departamentos e seus membros", Requires: []PermissionEntry{need(ResourceDepartments, ActionRead)}},
			{Key: "departments.create", Description: "Criar departamentos", Requires: []PermissionEntry{need(ResourceDepartments, ActionRead), need(ResourceDepartments, ActionCreate)}},
			{Key: "departments.edit", Description: "Editar departamentos, horários de atendimento e membros", Requires: []PermissionEntry{need(ResourceDepartments, ActionRead), need(ResourceDepartments, ActionUpdate)}},
			{Key: "departments.delete", Description: "Excluir departamentos", Requires: []PermissionEntry{need(ResourceDepartments, ActionRead), need(ResourceDepartments, ActionDelete)}},
		},
	},
	{
		Key:         "resource_access",
		Name:        "Acesso a recursos",
		Location:    "Menu lateral › Workspace › Permissões › Acesso a recursos",
		Description: "Atribuição de recursos específicos a membros.",
		Capabilities: []Capability{
			{Key: "resource_access.view", Description: "Ver quais membros têm acesso a cada recurso", Requires: []PermissionEntry{need(ResourceAssignments, ActionRead)}},
			{Key: "resource_access.grant", Description: "Dar a um membro acesso a um recurso específico", Requires: []PermissionEntry{need(ResourceAssignments, ActionCreate)}},
			{Key: "resource_access.revoke", Description: "Remover o acesso de um membro a um recurso", Requires: []PermissionEntry{need(ResourceAssignments, ActionDelete)}},
		},
	},
}
