package sip_trunk

import "errors"

var (
	ErrTrunkNotFound               = errors.New("sip trunk not found")
	ErrTrunkAlreadyExists          = errors.New("sip trunk already exists")
	ErrTrunkNameRequired           = errors.New("trunk name is required")
	ErrTrunkNameTooLong            = errors.New("trunk name is too long")
	ErrTrunkDescriptionTooLong     = errors.New("trunk description is too long")
	ErrTrunkHostRequired           = errors.New("trunk host is required")
	ErrTrunkHostInvalid            = errors.New("trunk host is invalid")
	ErrTrunkHostBlocked            = errors.New("trunk host is not allowed (loopback, private or link-local ranges are blocked)")
	ErrTrunkUsernameRequired       = errors.New("trunk username is required")
	ErrTrunkUsernameInvalid        = errors.New("trunk username is invalid")
	ErrTrunkPasswordRequired       = errors.New("trunk password is required")
	ErrTrunkPasswordInvalid        = errors.New("trunk password is invalid")
	ErrTrunkPortInvalid            = errors.New("trunk port must be between 1 and 65535")
	ErrTrunkTransportInvalid       = errors.New("invalid transport type")
	ErrTrunkTypeInvalid            = errors.New("invalid trunk type")
	ErrTrunkPhoneRequired          = errors.New("phone number is required for non-rotational trunks")
	ErrTrunkPhoneInvalid           = errors.New("trunk phone number is invalid")
	ErrTrunkCodecInvalid           = errors.New("invalid codec configuration")
	ErrTrunkDisabled               = errors.New("trunk is disabled")
	ErrTrunkNotRegistered          = errors.New("trunk is not registered")
	ErrTrunkForbidden              = errors.New("you don't have permission to modify this sip trunk")
	ErrTrunkGlobalForbidden        = errors.New("only administrators can publish trunks globally")
	ErrTrunkOwnerWorkspaceRequired = errors.New("owner workspace is required for sip trunk")
	ErrTrunkLimitReached           = errors.New("sip trunk limit reached for this workspace")

	ErrInboundNotOwned    = errors.New("sip trunk inbound rejected: trunk not owned by workspace")
	ErrInboundGlobalTrunk = errors.New("sip trunk inbound rejected: global trunks do not accept inbound calls")

	ErrTrunkNotOwnedHere = errors.New("sip trunk is not owned by this replica")
	ErrTrunkOwnerUnknown = errors.New("sip trunk owner replica is unknown")

	ErrTrunkUserAgentInvalid            = errors.New("user agent is too long (max 128 chars)")
	ErrTrunkOutboundProxyInvalid        = errors.New("outbound proxy is invalid")
	ErrTrunkRegisterExpiryInvalid       = errors.New("register expiry seconds must be between 1 and 86400")
	ErrTrunkRegisterRetryInvalid        = errors.New("register retry seconds must be between 1 and 3600")
	ErrTrunkMinSEInvalid                = errors.New("min session expires must be >= 90 seconds (RFC 4028)")
	ErrTrunkSessionTimerInvalid         = errors.New("session timer seconds must be >= 90 and >= min-SE")
	ErrTrunkSessionRefresherInvalid     = errors.New("invalid session refresher (must be uac, uas or empty)")
	ErrTrunkBindPortInvalid             = errors.New("bind port must be between 1 and 65535")
	ErrTrunkPublicAddressInvalid        = errors.New("public address is invalid")
	ErrTrunkStunServerInvalid           = errors.New("stun server must be host:port")
	ErrTrunkPTimeInvalid                = errors.New("ptime must be between 10 and 120 ms")
	ErrTrunkDTMFPayloadInvalid          = errors.New("dtmf payload type must be between 96 and 127 (RFC 3551)")
	ErrTrunkSRTPModeInvalid             = errors.New("invalid srtp mode")
	ErrTrunkSRTPRequiresSecureTransport = errors.New("srtp=required is only allowed with TCP or TLS transport")
	ErrTrunkDialPrefixInvalid           = errors.New("dial prefix is too long (max 16 chars)")
	ErrTrunkDialStripInvalid            = errors.New("dial strip digits must be between 0 and 16")
	ErrTrunkNumberFormatInvalid         = errors.New("invalid number format")
	ErrTrunkRingingTimeoutInvalid       = errors.New("ringing timeout must be between 5 and 600 seconds")

	ErrTrunkIdentityFieldInvalid = errors.New("identity field is too long or contains control characters")
	ErrTrunkStunServerBlocked    = errors.New("stun server host is not allowed (loopback, private or link-local)")
	ErrTrunkTooManyEntries       = errors.New("too many entries in list field")
)
