package workflow

import "errors"

var (
	ErrWorkflowNotFound         = errors.New("workflow: not found")
	ErrWorkspaceIDRequired      = errors.New("workflow: workspace id is required")
	ErrNameRequired             = errors.New("workflow: name is required")
	ErrInvalidTriggerType       = errors.New("workflow: invalid trigger type")
	ErrInvalidStatus            = errors.New("workflow: invalid status")
	ErrInvalidNodeType          = errors.New("workflow: invalid node type")
	ErrUnknownNodeType          = errors.New("workflow: node type does not exist in the node catalog")
	ErrWorkflowNotDraft         = errors.New("workflow: workflow must be in draft status to edit")
	ErrWorkflowNotActive        = errors.New("workflow: workflow is not active")
	ErrCannotActivate           = errors.New("workflow: cannot activate workflow")
	ErrInvalidWorkflowType      = errors.New("workflow: invalid workflow type")
	ErrTriggerNotAllowedForType = errors.New("workflow: trigger type is not allowed for this workflow type")

	ErrGraphEmpty                       = errors.New("workflow: graph has no nodes")
	ErrGraphNoTrigger                   = errors.New("workflow: graph must have exactly one trigger node")
	ErrGraphMultipleTriggers            = errors.New("workflow: graph must have exactly one trigger node, found multiple")
	ErrGraphNoEndNode                   = errors.New("workflow: graph must have at least one end node")
	ErrGraphOrphanNode                  = errors.New("workflow: graph has unreachable nodes")
	ErrGraphNodeNoOutgoing              = errors.New("workflow: non-end node must have at least one outgoing edge")
	ErrGraphNodeNoIncoming              = errors.New("workflow: non-trigger node must have at least one incoming edge")
	ErrGraphCycleDetected               = errors.New("workflow: graph contains a cycle")
	ErrGraphTooManyNodes                = errors.New("workflow: graph exceeds maximum node count")
	ErrGraphTooManyEdges                = errors.New("workflow: graph exceeds maximum edge count")
	ErrGraphInvalidEdgeRef              = errors.New("workflow: edge references a non-existent node")
	ErrGraphDuplicateNodeID             = errors.New("workflow: duplicate node id")
	ErrGraphTriggerTypeMismatch         = errors.New("workflow: trigger node type does not match workflow trigger type")
	ErrGraphDuplicateTriggerType        = errors.New("workflow: graph contains duplicate trigger nodes of the same type")
	ErrGraphTriggerIncompatibleWithType = errors.New("workflow: trigger node is not compatible with the workflow type")
	ErrGraphTriggerNotConnected         = errors.New("workflow: at least one trigger node must be connected to the flow")
	ErrNodeMissingRequiredField         = errors.New("workflow: node is missing a required config field")
	ErrNodeFieldOutOfRange              = errors.New("workflow: a numeric config field is outside its allowed range")
	ErrNodeMissingRequiredOutput        = errors.New("workflow: node is missing a required output edge")
	ErrNodeInvalidTemplateID            = errors.New("workflow: template ID is invalid or template not found")
	ErrNodeInvalidAgentID               = errors.New("workflow: agent ID is invalid or agent not found")
	ErrNodeInvalidMediaID               = errors.New("workflow: media ID is invalid or media not found")
	ErrNodeInvalidLabelID               = errors.New("workflow: label ID is invalid or label not found")
	ErrNodeInvalidDepartmentID          = errors.New("workflow: department ID is invalid or department not found")
	ErrNodeInvalidMemberID              = errors.New("workflow: member ID is invalid or member not found")
	ErrNodeInvalidBusinessPhoneID       = errors.New("workflow: business phone ID is invalid or business phone not found")
	ErrNodeInvalidWorkflowID            = errors.New("workflow: referenced workflow ID is invalid or workflow not found")
	ErrNodeInvalidMCPCollectionID       = errors.New("workflow: MCP collection ID is invalid or collection not found")
	ErrNodeInvalidKnowledgeBaseID       = errors.New("workflow: knowledge base ID is invalid or not found")
	ErrNodeInvalidModelID               = errors.New("workflow: AI model ID is invalid or not available from the provider")
	ErrNodeIncompatibleScope            = errors.New("workflow: node is incompatible with workflow trigger scope")
	ErrNodeInvalidToolMode              = errors.New("workflow: invalid tool_mode value (must be 'route' or 'execute')")
	ErrNodeInvalidToolParamType         = errors.New("workflow: a custom-tool parameter has an invalid type (must be a supported parameter type)")
	ErrNodeInvalidResponseMode          = errors.New("workflow: invalid response_mode value (must be 'default' or 'segmented')")
	ErrNodeSegmentedSendConflict        = errors.New("workflow: AI agent with segmented response_mode sends messages automatically — remove the downstream send_text node to avoid duplicate messages")
	ErrNodeInvalidInteractiveConfig     = errors.New("workflow: interactive prompt node has invalid buttons/list options (see WhatsApp limits)")

	ErrRunNotFound          = errors.New("workflow: run not found")
	ErrRunAlreadyExists     = errors.New("workflow: active run already exists for this workflow and entry")
	ErrRunNotWaiting        = errors.New("workflow: run is not in waiting status")
	ErrRunTerminal          = errors.New("workflow: run is in a terminal status")
	ErrWorkflowIDRequired   = errors.New("workflow: workflow id is required")
	ErrEntryIDRequired      = errors.New("workflow: entry id is required")
	ErrEntryTypeRequired    = errors.New("workflow: entry type is required")
	ErrMaxExecutionsReached = errors.New("workflow: maximum node executions reached (circuit breaker)")
	// ErrDurableExecutionsReached fires when a run exceeds the lifetime node-execution
	// cap across waits — the backstop for a loop that cycles through a wait node.
	ErrDurableExecutionsReached = errors.New("workflow: maximum lifetime node executions across waits reached (circuit breaker)")
	ErrInsufficientBalance      = errors.New("workflow: insufficient balance to execute node")

	ErrNodeExecutorNotFound = errors.New("workflow: no executor registered for node type")
	ErrNodeConfigMissing    = errors.New("workflow: required node config is missing")
)
