package calllist

import "errors"

var (
	ErrWorkspaceRequired   = errors.New("call list: workspace is required")
	ErrActorRequired       = errors.New("call list: the person acting is required")
	ErrForbidden           = errors.New("call list: you do not have the permissions this needs")
	ErrUnavailable         = errors.New("call list: call lists are not available on this server")
	ErrNameRequired        = errors.New("call list: a call list needs a name")
	ErrNameTooLong         = errors.New("call list: the name is too long")
	ErrAssigneesRequired   = errors.New("call list: a call list needs at least one member to call")
	ErrTooManyAssignees    = errors.New("call list: a call list has too many members to call")
	ErrAssigneeCannotWork  = errors.New("call list: a chosen member cannot work call lists")
	ErrPhoneChoiceInvalid  = errors.New("call list: choose the WhatsApp number or a known contact phone label")
	ErrSelectionEmpty      = errors.New("call list: the selection holds no lead")
	ErrSelectionTooLarge   = errors.New("call list: the selection is larger than a call list holds")
	ErrListNotFound        = errors.New("call list: not found")
	ErrItemNotFound        = errors.New("call list: item not found")
	ErrListBuilding        = errors.New("call list: the list is still being built")
	ErrListNotActive       = errors.New("call list: the list is not active")
	ErrNotAssignee         = errors.New("call list: you are not one of the members who call this list")
	ErrStatusTransition    = errors.New("call list: the list cannot move to this status")
	ErrNothingToChange     = errors.New("call list: send a name, the members or a status to change")
	ErrReservationHeld     = errors.New("call list: you already hold an item of another list, close or release it first")
	ErrItemTaken           = errors.New("call list: someone else is working on this item")
	ErrItemNotReserved     = errors.New("call list: this item is not reserved by you")
	ErrItemMismatch        = errors.New("call list: the call is not for the lead and number of this item")
	ErrItemClosed          = errors.New("call list: this item is already closed")
	ErrItemNotCalled       = errors.New("call list: call the lead before recording the outcome")
	ErrCallNotTheItems     = errors.New("call list: the call is not this item's own call")
	ErrDispositionRequired = errors.New("call list: choose an outcome")
	ErrDispositionUnknown  = errors.New("call list: the outcome is not in the workspace catalogue")
	ErrDispositionReserved = errors.New("call list: this outcome is reserved for the system")
	ErrNoOutcomes          = errors.New("call list: the workspace has no outcome catalogue, configure the outcomes first")
	ErrCallbackTime        = errors.New("call list: a callback needs a future time within 90 days, and only a callback takes a time")
	ErrNoteTooLong         = errors.New("call list: the note is too long")
	ErrBuildClaimLost      = errors.New("call list: another worker took over building this list")
	ErrBuildCursorInvalid  = errors.New("call list: the build cursor is not a lead id")
	ErrItemCursorInvalid   = errors.New("call list: a page of pending items needs the asOf instant of its first page")
)
