// Code generated from the frontend message catalogue. DO NOT EDIT.

package report_renderers

func ExportLabels() *StaticLabels {
	labels := NewStaticLabels("pt")
	labels.Add("pt", Labels{
		"metricsOps.export": {
			"actorKind.ai":                        "IA",
			"actorKind.human":                     "Humano",
			"actorKind.system":                    "System",
			"ai.abandoned":                        "Abandonadas",
			"ai.avgAiMessages":                    "Mensagens médias da IA",
			"ai.contained":                        "Resolvidas pela IA",
			"ai.containmentRate":                  "Taxa de contenção (%)",
			"ai.handedOff":                        "Transferidas",
			"ai.handoffRate":                      "Taxa de transferência (%)",
			"ai.openSessions":                     "Em aberto",
			"ai.sessions":                         "Sessões",
			"button":                              "Exportar CSV",
			"channel.instagram":                   "Instagram",
			"channel.telegram":                    "Telegram",
			"channel.whatsapp":                    "WhatsApp",
			"columns.actual":                      "Realizado",
			"columns.attainPct":                   "% da meta",
			"columns.avgDaysInStage":              "Dias parado (média)",
			"columns.avgHandleMins":               "Atendimento médio (min)",
			"columns.avgMessages":                 "Mensagens por conversa",
			"columns.avgResponseMins":             "Resposta média (min)",
			"columns.avgTicketCents":              "Ticket médio (centavos)",
			"columns.avgWaitMins":                 "Espera média (min)",
			"columns.bestBucket":                  "Melhor período",
			"columns.bestValue":                   "Melhor valor",
			"columns.bucket":                      "Período",
			"columns.captured":                    "Com desfecho",
			"columns.channel":                     "Canal",
			"columns.closedPct":                   "% fora da janela",
			"columns.closes":                      "Encerramentos",
			"columns.conversations":               "Conversas",
			"columns.count":                       "Total",
			"columns.currency":                    "Moeda",
			"columns.definition":                  "Definição",
			"columns.deltaPct":                    "Variação %",
			"columns.department":                  "Departamento",
			"columns.dimension":                   "Dimensão",
			"columns.durable":                     "Resolvidas de vez",
			"columns.durablePct":                  "% resolvidas de vez",
			"columns.email":                       "E-mail",
			"columns.engaged":                     "Conversas engajadas",
			"columns.filter":                      "Filtro",
			"columns.finished":                    "Finalizadas",
			"columns.finishedAi":                  "Finalizadas (IA)",
			"columns.finishedHuman":               "Finalizadas (humano)",
			"columns.finishedSystem":              "Finalizadas (sistema)",
			"columns.funnel":                      "Funil",
			"columns.hour":                        "Hora",
			"columns.kind":                        "Tipo",
			"columns.label":                       "Rótulo",
			"columns.measured":                    "Base medida",
			"columns.member":                      "Atendente",
			"columns.memberClass":                 "Faixa",
			"columns.metric":                      "Indicador",
			"columns.oldestDaysInStage":           "Dias parado (mais antiga)",
			"columns.ongoing":                     "Em andamento",
			"columns.open":                        "Abertas",
			"columns.partial":                     "Período incompleto",
			"columns.pctOfFunnel":                 "% do funil",
			"columns.pctOfStaged":                 "% do total em etapas",
			"columns.pctOfTeamAvg":                "% da média do time",
			"columns.pending":                     "Pendentes",
			"columns.perOnlineHour":               "Por hora online",
			"columns.perOpenDay":                  "Por dia útil",
			"columns.perOpenDayCents":             "Por dia útil (centavos)",
			"columns.percent":                     "%",
			"columns.presence":                    "Presença",
			"columns.prevClosedCents":             "Período anterior (centavos)",
			"columns.projected":                   "Projeção",
			"columns.projectedCents":              "Projeção (centavos)",
			"columns.projectedFlag":               "É projeção",
			"columns.rankMetricValue":             "Valor da métrica",
			"columns.rating":                      "Avaliação",
			"columns.reason":                      "Motivo",
			"columns.reopenRate":                  "% reabertas",
			"columns.reopened":                    "Reabertas",
			"columns.resolutionPct":               "Resolução (%)",
			"columns.resolved":                    "Resolvidas",
			"columns.revenueCents":                "Receita (centavos)",
			"columns.reworkCostMicros":            "Custo do retrabalho (micros)",
			"columns.reworkTemplates":             "Templates reenviados",
			"columns.shell":                       "Sem mensagem",
			"columns.stage":                       "Etapa",
			"columns.status":                      "Situação",
			"columns.stuck":                       "Travadas",
			"columns.stuckAfterDays":              "Limite (dias)",
			"columns.target":                      "Meta",
			"columns.total":                       "Total",
			"columns.totalMessages":               "Mensagens",
			"columns.unknown":                     "Sem informação",
			"columns.value":                       "Valor",
			"columns.valueCents":                  "Valor (centavos)",
			"columns.verdict":                     "Situação",
			"columns.windowClosed":                "Janela fechada",
			"columns.windowOpen":                  "Janela aberta",
			"columns.wonCount":                    "Negócios ganhos",
			"definitions.ai":                      "Atendimento por IA",
			"definitions.channel_mix":             "Mix de canais",
			"definitions.csat":                    "Satisfação (CSAT)",
			"definitions.engaged":                 "Conversa engajada",
			"definitions.finished_by_source":      "Origem da finalização",
			"definitions.frt":                     "Primeira resposta",
			"definitions.handle_time":             "Tempo de atendimento",
			"definitions.messaging":               "Mensagens",
			"definitions.new_leads":               "Novos contatos (leads)",
			"definitions.occupancy":               "Ocupação",
			"definitions.period_scope":            "Recorte do período",
			"definitions.queue":                   "Fila",
			"definitions.reopen":                  "Reabertura",
			"definitions.resolution":              "Resolução",
			"definitions.shell":                   "Entrada sem mensagens",
			"definitions.sla":                     "SLA",
			"definitions.stages":                  "Etapas do funil",
			"definitions.status_mapping":          "Mapeamento de situação",
			"definitions.unassigned":              "Sem atendente",
			"definitions.wait_time":               "Tempo de espera",
			"executive.atRisk":                    "Metas em risco",
			"executive.available":                 "Disponível",
			"executive.cluster":                   "Situação geral",
			"executive.elapsedPct":                "% do período decorrido",
			"executive.offTrack":                  "Metas fora da rota",
			"executive.onTrack":                   "Metas no caminho",
			"executive.openDaysDone":              "Dias úteis decorridos",
			"executive.openDaysLeft":              "Dias úteis restantes",
			"executive.openDaysTotal":             "Dias úteis no período",
			"executive.reason":                    "Motivo",
			"executive.targetsSet":                "Metas definidas",
			"executive.timezone":                  "Fuso horário",
			"expiredFile":                         "O arquivo expirou. Peça o relatório de novo.",
			"failed":                              "Não foi possível gerar o relatório",
			"failure.cancelled":                   "A geração foi cancelada.",
			"failure.render_failed":               "A geração falhou. Tente de novo em alguns minutos.",
			"failure.renderer_not_configured":     "Este relatório não está disponível neste servidor.",
			"failure.source_unavailable":          "A fonte dos dados não respondeu. Tente de novo.",
			"failure.too_many_rows":               "O período tem linhas demais. Escolha um intervalo menor.",
			"failure.unknown_kind":                "Este tipo de relatório não existe neste servidor.",
			"failure.unsupported_format":          "Este relatório não sai neste formato.",
			"failure.upload_failed":               "O arquivo foi gerado mas não pôde ser guardado. Tente de novo.",
			"failure.workspace_required":          "Escolha um workspace antes de exportar.",
			"filters.campaign":                    "Campanha",
			"filters.campaignType":                "Tipo de campanha",
			"filters.channel":                     "Canal",
			"filters.dateFrom":                    "Data inicial",
			"filters.dateTo":                      "Data final",
			"filters.department":                  "Departamento",
			"filters.generatedAt":                 "Gerado em",
			"filters.includeAi":                   "Incluir IA",
			"filters.member":                      "Atendente",
			"filters.workspace":                   "Área de trabalho",
			"finishedBySource.ai":                 "IA",
			"finishedBySource.human":              "Humano",
			"finishedBySource.system":             "Sistema",
			"finishedBySource.total":              "Total",
			"frt.aiAvgMins":                       "Média IA (min)",
			"frt.aiSamples":                       "Amostras IA",
			"frt.avgMins":                         "Média (min)",
			"frt.humanAvgMins":                    "Média humano (min)",
			"frt.humanSamples":                    "Amostras humano",
			"frt.medianMins":                      "Mediana (min)",
			"frt.sampleCount":                     "Amostras",
			"kpi.avgFrtMins":                      "Primeira resposta média (min)",
			"kpi.avgHandleMins":                   "Atendimento médio (min)",
			"kpi.avgRating":                       "Avaliação média",
			"kpi.avgWaitMins":                     "Espera média (min)",
			"kpi.engaged":                         "Conversas engajadas",
			"kpi.entriesCreated":                  "Entradas criadas",
			"kpi.finished":                        "Finalizadas",
			"kpi.frtSlaPercent":                   "SLA de primeira resposta (%)",
			"kpi.newLeads":                        "Novos contatos",
			"kpi.ongoing":                         "Em andamento",
			"kpi.pending":                         "Aguardando",
			"kpi.resolutionSlaPercent":            "SLA de resolução (%)",
			"kpi.shellBacklog":                    "Sem mensagens",
			"kpi.totalScoped":                     "Total no recorte",
			"kpi.unassignedBacklog":               "Sem atendente",
			"messaging.avgAllScoped":              "Média incluindo sem mensagens",
			"messaging.avgInbound":                "Média recebidas",
			"messaging.avgOutbound":               "Média enviadas",
			"messaging.avgPerConversation":        "Média por conversa",
			"messaging.avgTemplate":               "Média de templates",
			"messaging.conversationsWithMessages": "Conversas com mensagens",
			"messaging.conversationsWithTemplate": "Conversas com template",
			"messaging.templateMessages":          "Templates enviados",
			"no":                                  "Não",
			"noDepartment":                        "Sem departamento",
			"noFunnel":                            "Sem funil",
			"occupancy.agentsSampled":             "Atendentes amostrados",
			"occupancy.avgOccupancyPct":           "Ocupação média (%)",
			"occupancy.teamIdlePct":               "Ociosidade da equipe (%)",
			"occupancy.teamOccupancyPct":          "Ocupação da equipe (%)",
			"preparing":                           "Gerando…",
			"presence.offline":                    "Offline",
			"presence.on_call":                    "Em chamada",
			"presence.online":                     "Online",
			"queue.abandonRate":                   "Taxa de abandono (%)",
			"queue.abandoned":                     "Abandonadas",
			"queue.avgAsaMins":                    "Tempo médio de atendimento na fila (min)",
			"queue.cancelled":                     "Canceladas",
			"queue.connected":                     "Conectadas",
			"queue.enqueued":                      "Entraram na fila",
			"queue.overflow":                      "Transbordo",
			"queue.queueFull":                     "Fila cheia",
			"queued":                              "Na fila",
			"ready":                               "Relatório pronto, o download começou",
			"reopen.finishedCount":                "Finalizadas",
			"reopen.reopenRate":                   "Taxa de reabertura (%)",
			"reopen.reopenedCount":                "Reabertas",
			"running":                             "Gerando",
			"sections.ai":                         "Atendimento por IA",
			"sections.backlogXray":                "Raio-x da fila",
			"sections.channels":                   "Mix de canais",
			"sections.definitions":                "Definições dos indicadores",
			"sections.departments":                "Por departamento",
			"sections.filters":                    "Filtros aplicados",
			"sections.finishedBySource":           "Como foram finalizadas",
			"sections.frt":                        "Primeira resposta",
			"sections.hourly":                     "Conversas por hora",
			"sections.kpis":                       "Indicadores",
			"sections.members":                    "Por atendente",
			"sections.messaging":                  "Mensagens por conversa",
			"sections.occupancy":                  "Ocupação",
			"sections.period":                     "Período",
			"sections.projections":                "Projeções e metas",
			"sections.quality":                    "Qualidade do desfecho",
			"sections.queue":                      "Fila",
			"sections.reachability":               "Alcance por canal",
			"sections.reopen":                     "Reaberturas",
			"sections.revenue":                    "Receita",
			"sections.rework":                     "Retrabalho",
			"sections.stages":                     "Por etapa do funil",
			"sections.stagesTotals":               "Cobertura de etapas",
			"sections.status":                     "Situação das conversas",
			"sections.teamRanking":                "Ranking do time",
			"sections.trend":                      "Tendência",
			"stages.stagedEngaged":                "Conversas em etapas",
			"stages.stagedShell":                  "Sem mensagem em etapas",
			"stages.stuck":                        "Conversas travadas",
			"stages.unstagedEngaged":              "Conversas sem etapa",
			"stages.unstagedShell":                "Sem mensagem e sem etapa",
			"status.finished":                     "Finalizadas",
			"status.ongoing":                      "Em andamento",
			"status.pending":                      "Aguardando",
			"title":                               "Relatório de atendimento",
			"yes":                                 "Sim",
		},
	})
	labels.Add("en", Labels{
		"metricsOps.export": {
			"actorKind.ai":                        "AI",
			"actorKind.human":                     "Human",
			"actorKind.system":                    "System",
			"ai.abandoned":                        "Abandoned",
			"ai.avgAiMessages":                    "Avg AI messages",
			"ai.contained":                        "Resolved by AI",
			"ai.containmentRate":                  "Containment rate (%)",
			"ai.handedOff":                        "Handed off",
			"ai.handoffRate":                      "Handoff rate (%)",
			"ai.openSessions":                     "Open",
			"ai.sessions":                         "Sessions",
			"button":                              "Export CSV",
			"channel.instagram":                   "Instagram",
			"channel.telegram":                    "Telegram",
			"channel.whatsapp":                    "WhatsApp",
			"columns.actual":                      "Actual",
			"columns.attainPct":                   "% of target",
			"columns.avgDaysInStage":              "Days parked (avg)",
			"columns.avgHandleMins":               "Avg handle (min)",
			"columns.avgMessages":                 "Messages per chat",
			"columns.avgResponseMins":             "Avg response (min)",
			"columns.avgTicketCents":              "Average ticket (cents)",
			"columns.avgWaitMins":                 "Avg wait (min)",
			"columns.bestBucket":                  "Best bucket",
			"columns.bestValue":                   "Best value",
			"columns.bucket":                      "Bucket",
			"columns.captured":                    "With outcome",
			"columns.channel":                     "Channel",
			"columns.closedPct":                   "% outside window",
			"columns.closes":                      "Closes",
			"columns.conversations":               "Conversations",
			"columns.count":                       "Count",
			"columns.currency":                    "Currency",
			"columns.definition":                  "Definition",
			"columns.deltaPct":                    "Change %",
			"columns.department":                  "Department",
			"columns.dimension":                   "Dimension",
			"columns.durable":                     "Durably resolved",
			"columns.durablePct":                  "% durably resolved",
			"columns.email":                       "Email",
			"columns.engaged":                     "Engaged conversations",
			"columns.filter":                      "Filter",
			"columns.finished":                    "Finished",
			"columns.finishedAi":                  "Finished (AI)",
			"columns.finishedHuman":               "Finished (human)",
			"columns.finishedSystem":              "Finished (system)",
			"columns.funnel":                      "Funnel",
			"columns.hour":                        "Hour",
			"columns.kind":                        "Kind",
			"columns.label":                       "Label",
			"columns.measured":                    "Measured base",
			"columns.member":                      "Attendant",
			"columns.memberClass":                 "Band",
			"columns.metric":                      "Indicator",
			"columns.oldestDaysInStage":           "Days parked (oldest)",
			"columns.ongoing":                     "Ongoing",
			"columns.open":                        "Open",
			"columns.partial":                     "Partial period",
			"columns.pctOfFunnel":                 "% of funnel",
			"columns.pctOfStaged":                 "% of everything staged",
			"columns.pctOfTeamAvg":                "% of team average",
			"columns.pending":                     "Pending",
			"columns.perOnlineHour":               "Per online hour",
			"columns.perOpenDay":                  "Per open day",
			"columns.perOpenDayCents":             "Per open day (cents)",
			"columns.percent":                     "%",
			"columns.presence":                    "Presence",
			"columns.prevClosedCents":             "Previous period (cents)",
			"columns.projected":                   "Projected",
			"columns.projectedCents":              "Projected (cents)",
			"columns.projectedFlag":               "Is projected",
			"columns.rankMetricValue":             "Metric value",
			"columns.rating":                      "Rating",
			"columns.reason":                      "Reason",
			"columns.reopenRate":                  "% reopened",
			"columns.reopened":                    "Reopened",
			"columns.resolutionPct":               "Resolution (%)",
			"columns.resolved":                    "Resolved",
			"columns.revenueCents":                "Revenue (cents)",
			"columns.reworkCostMicros":            "Rework cost (micros)",
			"columns.reworkTemplates":             "Templates resent",
			"columns.shell":                       "No message",
			"columns.stage":                       "Stage",
			"columns.status":                      "Status",
			"columns.stuck":                       "Stalled",
			"columns.stuckAfterDays":              "Threshold (days)",
			"columns.target":                      "Target",
			"columns.total":                       "Total",
			"columns.totalMessages":               "Messages",
			"columns.unknown":                     "Unknown",
			"columns.value":                       "Value",
			"columns.valueCents":                  "Value (cents)",
			"columns.verdict":                     "Verdict",
			"columns.windowClosed":                "Window closed",
			"columns.windowOpen":                  "Window open",
			"columns.wonCount":                    "Deals won",
			"definitions.ai":                      "AI handling",
			"definitions.channel_mix":             "Channel mix",
			"definitions.csat":                    "Satisfaction (CSAT)",
			"definitions.engaged":                 "Engaged conversation",
			"definitions.finished_by_source":      "Finish source",
			"definitions.frt":                     "First response",
			"definitions.handle_time":             "Handle time",
			"definitions.messaging":               "Messaging",
			"definitions.new_leads":               "New contacts (leads)",
			"definitions.occupancy":               "Occupancy",
			"definitions.period_scope":            "Period scope",
			"definitions.queue":                   "Queue",
			"definitions.reopen":                  "Reopen",
			"definitions.resolution":              "Resolution",
			"definitions.shell":                   "Entry without messages",
			"definitions.sla":                     "SLA",
			"definitions.stages":                  "Funnel stages",
			"definitions.status_mapping":          "Status mapping",
			"definitions.unassigned":              "Unassigned",
			"definitions.wait_time":               "Wait time",
			"executive.atRisk":                    "Targets at risk",
			"executive.available":                 "Available",
			"executive.cluster":                   "Overall standing",
			"executive.elapsedPct":                "% of period elapsed",
			"executive.offTrack":                  "Targets off track",
			"executive.onTrack":                   "Targets on track",
			"executive.openDaysDone":              "Open days elapsed",
			"executive.openDaysLeft":              "Open days left",
			"executive.openDaysTotal":             "Open days in period",
			"executive.reason":                    "Reason",
			"executive.targetsSet":                "Targets set",
			"executive.timezone":                  "Timezone",
			"expiredFile":                         "The file has expired. Request the report again.",
			"failed":                              "The report could not be generated",
			"failure.cancelled":                   "Generation was cancelled.",
			"failure.render_failed":               "Generation failed. Try again in a few minutes.",
			"failure.renderer_not_configured":     "This report is not available on this server.",
			"failure.source_unavailable":          "The data source did not respond. Try again.",
			"failure.too_many_rows":               "The period has too many rows. Pick a shorter range.",
			"failure.unknown_kind":                "This report type does not exist on this server.",
			"failure.unsupported_format":          "This report is not available in that format.",
			"failure.upload_failed":               "The file was generated but could not be stored. Try again.",
			"failure.workspace_required":          "Pick a workspace before exporting.",
			"filters.campaign":                    "Campaign",
			"filters.campaignType":                "Campaign type",
			"filters.channel":                     "Channel",
			"filters.dateFrom":                    "Start date",
			"filters.dateTo":                      "End date",
			"filters.department":                  "Department",
			"filters.generatedAt":                 "Generated at",
			"filters.includeAi":                   "Include AI",
			"filters.member":                      "Attendant",
			"filters.workspace":                   "Workspace",
			"finishedBySource.ai":                 "AI",
			"finishedBySource.human":              "Human",
			"finishedBySource.system":             "System",
			"finishedBySource.total":              "Total",
			"frt.aiAvgMins":                       "AI average (min)",
			"frt.aiSamples":                       "AI samples",
			"frt.avgMins":                         "Average (min)",
			"frt.humanAvgMins":                    "Human average (min)",
			"frt.humanSamples":                    "Human samples",
			"frt.medianMins":                      "Median (min)",
			"frt.sampleCount":                     "Samples",
			"kpi.avgFrtMins":                      "Avg first response (min)",
			"kpi.avgHandleMins":                   "Avg handle (min)",
			"kpi.avgRating":                       "Avg rating",
			"kpi.avgWaitMins":                     "Avg wait (min)",
			"kpi.engaged":                         "Engaged conversations",
			"kpi.entriesCreated":                  "Entries created",
			"kpi.finished":                        "Finished",
			"kpi.frtSlaPercent":                   "First response SLA (%)",
			"kpi.newLeads":                        "New contacts",
			"kpi.ongoing":                         "Ongoing",
			"kpi.pending":                         "Waiting",
			"kpi.resolutionSlaPercent":            "Resolution SLA (%)",
			"kpi.shellBacklog":                    "Without messages",
			"kpi.totalScoped":                     "Total in scope",
			"kpi.unassignedBacklog":               "Unassigned",
			"messaging.avgAllScoped":              "Avg including empty",
			"messaging.avgInbound":                "Avg inbound",
			"messaging.avgOutbound":               "Avg outbound",
			"messaging.avgPerConversation":        "Avg per conversation",
			"messaging.avgTemplate":               "Avg templates",
			"messaging.conversationsWithMessages": "Conversations with messages",
			"messaging.conversationsWithTemplate": "Conversations with template",
			"messaging.templateMessages":          "Template messages",
			"no":                                  "No",
			"noDepartment":                        "No department",
			"noFunnel":                            "No funnel",
			"occupancy.agentsSampled":             "Agents sampled",
			"occupancy.avgOccupancyPct":           "Avg occupancy (%)",
			"occupancy.teamIdlePct":               "Team idle (%)",
			"occupancy.teamOccupancyPct":          "Team occupancy (%)",
			"preparing":                           "Generating…",
			"presence.offline":                    "Offline",
			"presence.on_call":                    "On call",
			"presence.online":                     "Online",
			"queue.abandonRate":                   "Abandon rate (%)",
			"queue.abandoned":                     "Abandoned",
			"queue.avgAsaMins":                    "Average speed of answer (min)",
			"queue.cancelled":                     "Cancelled",
			"queue.connected":                     "Connected",
			"queue.enqueued":                      "Enqueued",
			"queue.overflow":                      "Overflow",
			"queue.queueFull":                     "Queue full",
			"queued":                              "Queued",
			"ready":                               "Report ready, the download has started",
			"reopen.finishedCount":                "Finished",
			"reopen.reopenRate":                   "Reopen rate (%)",
			"reopen.reopenedCount":                "Reopened",
			"running":                             "Generating",
			"sections.ai":                         "AI handling",
			"sections.backlogXray":                "Backlog x-ray",
			"sections.channels":                   "Channel mix",
			"sections.definitions":                "Metric definitions",
			"sections.departments":                "By department",
			"sections.filters":                    "Applied filters",
			"sections.finishedBySource":           "How they were finished",
			"sections.frt":                        "First response",
			"sections.hourly":                     "Conversations by hour",
			"sections.kpis":                       "Indicators",
			"sections.members":                    "By attendant",
			"sections.messaging":                  "Messages per conversation",
			"sections.occupancy":                  "Occupancy",
			"sections.period":                     "Period",
			"sections.projections":                "Projections and targets",
			"sections.quality":                    "Outcome quality",
			"sections.queue":                      "Queue",
			"sections.reachability":               "Reachability by channel",
			"sections.reopen":                     "Reopens",
			"sections.revenue":                    "Revenue",
			"sections.rework":                     "Rework",
			"sections.stages":                     "By funnel stage",
			"sections.stagesTotals":               "Stage coverage",
			"sections.status":                     "Conversation status",
			"sections.teamRanking":                "Team ranking",
			"sections.trend":                      "Trend",
			"stages.stagedEngaged":                "Conversations in stages",
			"stages.stagedShell":                  "No message, in stages",
			"stages.stuck":                        "Stalled conversations",
			"stages.unstagedEngaged":              "Conversations with no stage",
			"stages.unstagedShell":                "No message and no stage",
			"status.finished":                     "Finished",
			"status.ongoing":                      "Ongoing",
			"status.pending":                      "Waiting",
			"title":                               "Attendance report",
			"yes":                                 "Yes",
		},
	})
	labels.Add("es", Labels{
		"metricsOps.export": {
			"actorKind.ai":                        "IA",
			"actorKind.human":                     "Humano",
			"actorKind.system":                    "System",
			"ai.abandoned":                        "Abandonadas",
			"ai.avgAiMessages":                    "Mensajes medios de IA",
			"ai.contained":                        "Resueltas por IA",
			"ai.containmentRate":                  "Tasa de contención (%)",
			"ai.handedOff":                        "Transferidas",
			"ai.handoffRate":                      "Tasa de transferencia (%)",
			"ai.openSessions":                     "Abiertas",
			"ai.sessions":                         "Sesiones",
			"button":                              "Exportar CSV",
			"channel.instagram":                   "Instagram",
			"channel.telegram":                    "Telegram",
			"channel.whatsapp":                    "WhatsApp",
			"columns.actual":                      "Real",
			"columns.attainPct":                   "% del objetivo",
			"columns.avgDaysInStage":              "Días detenido (promedio)",
			"columns.avgHandleMins":               "Atención media (min)",
			"columns.avgMessages":                 "Mensajes por conversación",
			"columns.avgResponseMins":             "Respuesta media (min)",
			"columns.avgTicketCents":              "Ticket medio (centavos)",
			"columns.avgWaitMins":                 "Espera media (min)",
			"columns.bestBucket":                  "Mejor periodo",
			"columns.bestValue":                   "Mejor valor",
			"columns.bucket":                      "Periodo",
			"columns.captured":                    "Con desenlace",
			"columns.channel":                     "Canal",
			"columns.closedPct":                   "% fuera de la ventana",
			"columns.closes":                      "Cierres",
			"columns.conversations":               "Conversaciones",
			"columns.count":                       "Total",
			"columns.currency":                    "Moneda",
			"columns.definition":                  "Definición",
			"columns.deltaPct":                    "Variación %",
			"columns.department":                  "Departamento",
			"columns.dimension":                   "Dimensión",
			"columns.durable":                     "Resueltas de verdad",
			"columns.durablePct":                  "% resueltas de verdad",
			"columns.email":                       "Correo",
			"columns.engaged":                     "Conversaciones con actividad",
			"columns.filter":                      "Filtro",
			"columns.finished":                    "Finalizadas",
			"columns.finishedAi":                  "Finalizadas (IA)",
			"columns.finishedHuman":               "Finalizadas (humano)",
			"columns.finishedSystem":              "Finalizadas (sistema)",
			"columns.funnel":                      "Embudo",
			"columns.hour":                        "Hora",
			"columns.kind":                        "Tipo",
			"columns.label":                       "Etiqueta",
			"columns.measured":                    "Base medida",
			"columns.member":                      "Agente",
			"columns.memberClass":                 "Banda",
			"columns.metric":                      "Indicador",
			"columns.oldestDaysInStage":           "Días detenido (más antigua)",
			"columns.ongoing":                     "En curso",
			"columns.open":                        "Abiertas",
			"columns.partial":                     "Periodo incompleto",
			"columns.pctOfFunnel":                 "% del embudo",
			"columns.pctOfStaged":                 "% del total en etapas",
			"columns.pctOfTeamAvg":                "% del promedio del equipo",
			"columns.pending":                     "Pendientes",
			"columns.perOnlineHour":               "Por hora en línea",
			"columns.perOpenDay":                  "Por día hábil",
			"columns.perOpenDayCents":             "Por día hábil (centavos)",
			"columns.percent":                     "%",
			"columns.presence":                    "Presencia",
			"columns.prevClosedCents":             "Periodo anterior (centavos)",
			"columns.projected":                   "Proyección",
			"columns.projectedCents":              "Proyección (centavos)",
			"columns.projectedFlag":               "Es proyección",
			"columns.rankMetricValue":             "Valor de la métrica",
			"columns.rating":                      "Valoración",
			"columns.reason":                      "Motivo",
			"columns.reopenRate":                  "% reabiertas",
			"columns.reopened":                    "Reabiertas",
			"columns.resolutionPct":               "Resolución (%)",
			"columns.resolved":                    "Resueltas",
			"columns.revenueCents":                "Ingresos (centavos)",
			"columns.reworkCostMicros":            "Costo del retrabajo (micros)",
			"columns.reworkTemplates":             "Plantillas reenviadas",
			"columns.shell":                       "Sin mensaje",
			"columns.stage":                       "Etapa",
			"columns.status":                      "Situación",
			"columns.stuck":                       "Estancadas",
			"columns.stuckAfterDays":              "Límite (días)",
			"columns.target":                      "Objetivo",
			"columns.total":                       "Total",
			"columns.totalMessages":               "Mensajes",
			"columns.unknown":                     "Sin información",
			"columns.value":                       "Valor",
			"columns.valueCents":                  "Valor (centavos)",
			"columns.verdict":                     "Situación",
			"columns.windowClosed":                "Ventana cerrada",
			"columns.windowOpen":                  "Ventana abierta",
			"columns.wonCount":                    "Negocios ganados",
			"definitions.ai":                      "Atención por IA",
			"definitions.channel_mix":             "Mezcla de canales",
			"definitions.csat":                    "Satisfacción (CSAT)",
			"definitions.engaged":                 "Conversación con actividad",
			"definitions.finished_by_source":      "Origen de la finalización",
			"definitions.frt":                     "Primera respuesta",
			"definitions.handle_time":             "Tiempo de atención",
			"definitions.messaging":               "Mensajes",
			"definitions.new_leads":               "Nuevos contactos (leads)",
			"definitions.occupancy":               "Ocupación",
			"definitions.period_scope":            "Recorte del período",
			"definitions.queue":                   "Cola",
			"definitions.reopen":                  "Reapertura",
			"definitions.resolution":              "Resolución",
			"definitions.shell":                   "Entrada sin mensajes",
			"definitions.sla":                     "SLA",
			"definitions.stages":                  "Etapas del embudo",
			"definitions.status_mapping":          "Mapeo de situación",
			"definitions.unassigned":              "Sin agente",
			"definitions.wait_time":               "Tiempo de espera",
			"executive.atRisk":                    "Objetivos en riesgo",
			"executive.available":                 "Disponible",
			"executive.cluster":                   "Situación general",
			"executive.elapsedPct":                "% del periodo transcurrido",
			"executive.offTrack":                  "Objetivos fuera de ruta",
			"executive.onTrack":                   "Objetivos en camino",
			"executive.openDaysDone":              "Días hábiles transcurridos",
			"executive.openDaysLeft":              "Días hábiles restantes",
			"executive.openDaysTotal":             "Días hábiles del periodo",
			"executive.reason":                    "Motivo",
			"executive.targetsSet":                "Objetivos definidos",
			"executive.timezone":                  "Zona horaria",
			"expiredFile":                         "El archivo ha expirado. Pide el informe de nuevo.",
			"failed":                              "No se pudo generar el informe",
			"failure.cancelled":                   "La generación fue cancelada.",
			"failure.render_failed":               "La generación falló. Inténtalo de nuevo en unos minutos.",
			"failure.renderer_not_configured":     "Este informe no está disponible en este servidor.",
			"failure.source_unavailable":          "La fuente de datos no respondió. Inténtalo de nuevo.",
			"failure.too_many_rows":               "El periodo tiene demasiadas filas. Elige un rango menor.",
			"failure.unknown_kind":                "Este tipo de informe no existe en este servidor.",
			"failure.unsupported_format":          "Este informe no está disponible en ese formato.",
			"failure.upload_failed":               "El archivo se generó pero no se pudo guardar. Inténtalo de nuevo.",
			"failure.workspace_required":          "Elige un espacio de trabajo antes de exportar.",
			"filters.campaign":                    "Campaña",
			"filters.campaignType":                "Tipo de campaña",
			"filters.channel":                     "Canal",
			"filters.dateFrom":                    "Fecha inicial",
			"filters.dateTo":                      "Fecha final",
			"filters.department":                  "Departamento",
			"filters.generatedAt":                 "Generado el",
			"filters.includeAi":                   "Incluir IA",
			"filters.member":                      "Agente",
			"filters.workspace":                   "Espacio de trabajo",
			"finishedBySource.ai":                 "IA",
			"finishedBySource.human":              "Humano",
			"finishedBySource.system":             "Sistema",
			"finishedBySource.total":              "Total",
			"frt.aiAvgMins":                       "Media IA (min)",
			"frt.aiSamples":                       "Muestras IA",
			"frt.avgMins":                         "Media (min)",
			"frt.humanAvgMins":                    "Media humano (min)",
			"frt.humanSamples":                    "Muestras humano",
			"frt.medianMins":                      "Mediana (min)",
			"frt.sampleCount":                     "Muestras",
			"kpi.avgFrtMins":                      "Primera respuesta media (min)",
			"kpi.avgHandleMins":                   "Atención media (min)",
			"kpi.avgRating":                       "Valoración media",
			"kpi.avgWaitMins":                     "Espera media (min)",
			"kpi.engaged":                         "Conversaciones con actividad",
			"kpi.entriesCreated":                  "Entradas creadas",
			"kpi.finished":                        "Finalizadas",
			"kpi.frtSlaPercent":                   "SLA de primera respuesta (%)",
			"kpi.newLeads":                        "Nuevos contactos",
			"kpi.ongoing":                         "En curso",
			"kpi.pending":                         "Esperando",
			"kpi.resolutionSlaPercent":            "SLA de resolución (%)",
			"kpi.shellBacklog":                    "Sin mensajes",
			"kpi.totalScoped":                     "Total en el recorte",
			"kpi.unassignedBacklog":               "Sin agente",
			"messaging.avgAllScoped":              "Media incluyendo vacías",
			"messaging.avgInbound":                "Media recibidos",
			"messaging.avgOutbound":               "Media enviados",
			"messaging.avgPerConversation":        "Media por conversación",
			"messaging.avgTemplate":               "Media de plantillas",
			"messaging.conversationsWithMessages": "Conversaciones con mensajes",
			"messaging.conversationsWithTemplate": "Conversaciones con plantilla",
			"messaging.templateMessages":          "Plantillas enviadas",
			"no":                                  "No",
			"noDepartment":                        "Sin departamento",
			"noFunnel":                            "Sin embudo",
			"occupancy.agentsSampled":             "Agentes muestreados",
			"occupancy.avgOccupancyPct":           "Ocupación media (%)",
			"occupancy.teamIdlePct":               "Inactividad del equipo (%)",
			"occupancy.teamOccupancyPct":          "Ocupación del equipo (%)",
			"preparing":                           "Generando…",
			"presence.offline":                    "Desconectado",
			"presence.on_call":                    "En llamada",
			"presence.online":                     "En línea",
			"queue.abandonRate":                   "Tasa de abandono (%)",
			"queue.abandoned":                     "Abandonadas",
			"queue.avgAsaMins":                    "Tiempo medio de respuesta en cola (min)",
			"queue.cancelled":                     "Canceladas",
			"queue.connected":                     "Conectadas",
			"queue.enqueued":                      "En cola",
			"queue.overflow":                      "Desbordamiento",
			"queue.queueFull":                     "Cola llena",
			"queued":                              "En cola",
			"ready":                               "Informe listo, la descarga ha comenzado",
			"reopen.finishedCount":                "Finalizadas",
			"reopen.reopenRate":                   "Tasa de reapertura (%)",
			"reopen.reopenedCount":                "Reabiertas",
			"running":                             "Generando",
			"sections.ai":                         "Atención por IA",
			"sections.backlogXray":                "Radiografía de la cola",
			"sections.channels":                   "Mezcla de canales",
			"sections.definitions":                "Definiciones de los indicadores",
			"sections.departments":                "Por departamento",
			"sections.filters":                    "Filtros aplicados",
			"sections.finishedBySource":           "Cómo se finalizaron",
			"sections.frt":                        "Primera respuesta",
			"sections.hourly":                     "Conversaciones por hora",
			"sections.kpis":                       "Indicadores",
			"sections.members":                    "Por agente",
			"sections.messaging":                  "Mensajes por conversación",
			"sections.occupancy":                  "Ocupación",
			"sections.period":                     "Periodo",
			"sections.projections":                "Proyecciones y objetivos",
			"sections.quality":                    "Calidad del desenlace",
			"sections.queue":                      "Cola",
			"sections.reachability":               "Alcance por canal",
			"sections.reopen":                     "Reaperturas",
			"sections.revenue":                    "Ingresos",
			"sections.rework":                     "Retrabajo",
			"sections.stages":                     "Por etapa del embudo",
			"sections.stagesTotals":               "Cobertura de etapas",
			"sections.status":                     "Situación de las conversaciones",
			"sections.teamRanking":                "Ranking del equipo",
			"sections.trend":                      "Tendencia",
			"stages.stagedEngaged":                "Conversaciones en etapas",
			"stages.stagedShell":                  "Sin mensaje, en etapas",
			"stages.stuck":                        "Conversaciones estancadas",
			"stages.unstagedEngaged":              "Conversaciones sin etapa",
			"stages.unstagedShell":                "Sin mensaje y sin etapa",
			"status.finished":                     "Finalizadas",
			"status.ongoing":                      "En curso",
			"status.pending":                      "Esperando",
			"title":                               "Informe de atención",
			"yes":                                 "Sí",
		},
	})
	labels.Add("de", Labels{
		"metricsOps.export": {
			"actorKind.ai":                        "KI",
			"actorKind.human":                     "Mensch",
			"actorKind.system":                    "System",
			"ai.abandoned":                        "Abgebrochen",
			"ai.avgAiMessages":                    "Ø KI-Nachrichten",
			"ai.contained":                        "Von KI gelöst",
			"ai.containmentRate":                  "Lösungsquote (%)",
			"ai.handedOff":                        "Übergeben",
			"ai.handoffRate":                      "Übergabequote (%)",
			"ai.openSessions":                     "Offen",
			"ai.sessions":                         "Sitzungen",
			"button":                              "CSV exportieren",
			"channel.instagram":                   "Instagram",
			"channel.telegram":                    "Telegram",
			"channel.whatsapp":                    "WhatsApp",
			"columns.actual":                      "Ist",
			"columns.attainPct":                   "% des Ziels",
			"columns.avgDaysInStage":              "Tage stehend (Durchschnitt)",
			"columns.avgHandleMins":               "Ø Bearbeitung (Min.)",
			"columns.avgMessages":                 "Nachrichten pro Chat",
			"columns.avgResponseMins":             "Ø Antwort (Min.)",
			"columns.avgTicketCents":              "Durchschnittsbon (Cent)",
			"columns.avgWaitMins":                 "Ø Wartezeit (Min.)",
			"columns.bestBucket":                  "Bester Zeitraum",
			"columns.bestValue":                   "Bester Wert",
			"columns.bucket":                      "Zeitraum",
			"columns.captured":                    "Mit Ergebnis",
			"columns.channel":                     "Kanal",
			"columns.closedPct":                   "% außerhalb des Fensters",
			"columns.closes":                      "Abschlüsse",
			"columns.conversations":               "Konversationen",
			"columns.count":                       "Anzahl",
			"columns.currency":                    "Währung",
			"columns.definition":                  "Definition",
			"columns.deltaPct":                    "Veränderung %",
			"columns.department":                  "Abteilung",
			"columns.dimension":                   "Dimension",
			"columns.durable":                     "Dauerhaft gelöst",
			"columns.durablePct":                  "% dauerhaft gelöst",
			"columns.email":                       "E-Mail",
			"columns.engaged":                     "Aktive Konversationen",
			"columns.filter":                      "Filter",
			"columns.finished":                    "Abgeschlossen",
			"columns.finishedAi":                  "Abgeschlossen (KI)",
			"columns.finishedHuman":               "Abgeschlossen (Mensch)",
			"columns.finishedSystem":              "Abgeschlossen (System)",
			"columns.funnel":                      "Funnel",
			"columns.hour":                        "Stunde",
			"columns.kind":                        "Art",
			"columns.label":                       "Bezeichnung",
			"columns.measured":                    "Gemessene Basis",
			"columns.member":                      "Mitarbeiter",
			"columns.memberClass":                 "Klasse",
			"columns.metric":                      "Kennzahl",
			"columns.oldestDaysInStage":           "Tage stehend (älteste)",
			"columns.ongoing":                     "Laufend",
			"columns.open":                        "Offen",
			"columns.partial":                     "Unvollständiger Zeitraum",
			"columns.pctOfFunnel":                 "% des Funnels",
			"columns.pctOfStaged":                 "% aller Phasen",
			"columns.pctOfTeamAvg":                "% des Teamdurchschnitts",
			"columns.pending":                     "Ausstehend",
			"columns.perOnlineHour":               "Pro Online-Stunde",
			"columns.perOpenDay":                  "Pro Arbeitstag",
			"columns.perOpenDayCents":             "Pro Arbeitstag (Cent)",
			"columns.percent":                     "%",
			"columns.presence":                    "Präsenz",
			"columns.prevClosedCents":             "Vorheriger Zeitraum (Cent)",
			"columns.projected":                   "Prognose",
			"columns.projectedCents":              "Prognose (Cent)",
			"columns.projectedFlag":               "Ist Prognose",
			"columns.rankMetricValue":             "Metrikwert",
			"columns.rating":                      "Bewertung",
			"columns.reason":                      "Grund",
			"columns.reopenRate":                  "% wieder geöffnet",
			"columns.reopened":                    "Wieder geöffnet",
			"columns.resolutionPct":               "Lösung (%)",
			"columns.resolved":                    "Gelöst",
			"columns.revenueCents":                "Umsatz (Cent)",
			"columns.reworkCostMicros":            "Nacharbeitskosten (Mikro)",
			"columns.reworkTemplates":             "Erneut gesendete Vorlagen",
			"columns.shell":                       "Ohne Nachricht",
			"columns.stage":                       "Phase",
			"columns.status":                      "Status",
			"columns.stuck":                       "Festgefahren",
			"columns.stuckAfterDays":              "Schwelle (Tage)",
			"columns.target":                      "Ziel",
			"columns.total":                       "Gesamt",
			"columns.totalMessages":               "Nachrichten",
			"columns.unknown":                     "Unbekannt",
			"columns.value":                       "Wert",
			"columns.valueCents":                  "Wert (Cent)",
			"columns.verdict":                     "Bewertung",
			"columns.windowClosed":                "Fenster geschlossen",
			"columns.windowOpen":                  "Fenster offen",
			"columns.wonCount":                    "Gewonnene Deals",
			"definitions.ai":                      "KI-Bearbeitung",
			"definitions.channel_mix":             "Kanalverteilung",
			"definitions.csat":                    "Zufriedenheit (CSAT)",
			"definitions.engaged":                 "Aktive Konversation",
			"definitions.finished_by_source":      "Abschlussart",
			"definitions.frt":                     "Erste Antwort",
			"definitions.handle_time":             "Bearbeitungszeit",
			"definitions.messaging":               "Nachrichten",
			"definitions.new_leads":               "Neue Kontakte (Leads)",
			"definitions.occupancy":               "Auslastung",
			"definitions.period_scope":            "Zeitraum",
			"definitions.queue":                   "Warteschlange",
			"definitions.reopen":                  "Wiedereröffnung",
			"definitions.resolution":              "Lösung",
			"definitions.shell":                   "Eintrag ohne Nachrichten",
			"definitions.sla":                     "SLA",
			"definitions.stages":                  "Funnel-Phasen",
			"definitions.status_mapping":          "Status-Zuordnung",
			"definitions.unassigned":              "Ohne Zuweisung",
			"definitions.wait_time":               "Wartezeit",
			"executive.atRisk":                    "Ziele in Gefahr",
			"executive.available":                 "Verfügbar",
			"executive.cluster":                   "Gesamtstand",
			"executive.elapsedPct":                "% des Zeitraums vergangen",
			"executive.offTrack":                  "Ziele abseits der Spur",
			"executive.onTrack":                   "Ziele auf Kurs",
			"executive.openDaysDone":              "Vergangene Arbeitstage",
			"executive.openDaysLeft":              "Verbleibende Arbeitstage",
			"executive.openDaysTotal":             "Arbeitstage im Zeitraum",
			"executive.reason":                    "Grund",
			"executive.targetsSet":                "Gesetzte Ziele",
			"executive.timezone":                  "Zeitzone",
			"expiredFile":                         "Die Datei ist abgelaufen. Fordere den Bericht erneut an.",
			"failed":                              "Der Bericht konnte nicht erstellt werden",
			"failure.cancelled":                   "Die Erstellung wurde abgebrochen.",
			"failure.render_failed":               "Die Erstellung ist fehlgeschlagen. Versuche es in ein paar Minuten erneut.",
			"failure.renderer_not_configured":     "Dieser Bericht ist auf diesem Server nicht verfügbar.",
			"failure.source_unavailable":          "Die Datenquelle hat nicht geantwortet. Versuche es erneut.",
			"failure.too_many_rows":               "Der Zeitraum hat zu viele Zeilen. Wähle einen kürzeren Bereich.",
			"failure.unknown_kind":                "Diesen Berichtstyp gibt es auf diesem Server nicht.",
			"failure.unsupported_format":          "Diesen Bericht gibt es nicht in diesem Format.",
			"failure.upload_failed":               "Die Datei wurde erstellt, konnte aber nicht gespeichert werden. Versuche es erneut.",
			"failure.workspace_required":          "Wähle einen Workspace, bevor du exportierst.",
			"filters.campaign":                    "Kampagne",
			"filters.campaignType":                "Kampagnentyp",
			"filters.channel":                     "Kanal",
			"filters.dateFrom":                    "Startdatum",
			"filters.dateTo":                      "Enddatum",
			"filters.department":                  "Abteilung",
			"filters.generatedAt":                 "Erstellt am",
			"filters.includeAi":                   "KI einbeziehen",
			"filters.member":                      "Mitarbeiter",
			"filters.workspace":                   "Arbeitsbereich",
			"finishedBySource.ai":                 "KI",
			"finishedBySource.human":              "Mensch",
			"finishedBySource.system":             "System",
			"finishedBySource.total":              "Gesamt",
			"frt.aiAvgMins":                       "Ø KI (Min.)",
			"frt.aiSamples":                       "Stichproben KI",
			"frt.avgMins":                         "Durchschnitt (Min.)",
			"frt.humanAvgMins":                    "Ø Mensch (Min.)",
			"frt.humanSamples":                    "Stichproben Mensch",
			"frt.medianMins":                      "Median (Min.)",
			"frt.sampleCount":                     "Stichproben",
			"kpi.avgFrtMins":                      "Ø erste Antwort (Min.)",
			"kpi.avgHandleMins":                   "Ø Bearbeitung (Min.)",
			"kpi.avgRating":                       "Ø Bewertung",
			"kpi.avgWaitMins":                     "Ø Wartezeit (Min.)",
			"kpi.engaged":                         "Aktive Konversationen",
			"kpi.entriesCreated":                  "Erstellte Einträge",
			"kpi.finished":                        "Abgeschlossen",
			"kpi.frtSlaPercent":                   "SLA erste Antwort (%)",
			"kpi.newLeads":                        "Neue Kontakte",
			"kpi.ongoing":                         "Laufend",
			"kpi.pending":                         "Wartend",
			"kpi.resolutionSlaPercent":            "SLA Lösung (%)",
			"kpi.shellBacklog":                    "Ohne Nachrichten",
			"kpi.totalScoped":                     "Gesamt im Zeitraum",
			"kpi.unassignedBacklog":               "Ohne Zuweisung",
			"messaging.avgAllScoped":              "Ø inkl. leerer",
			"messaging.avgInbound":                "Ø eingehend",
			"messaging.avgOutbound":               "Ø ausgehend",
			"messaging.avgPerConversation":        "Ø pro Konversation",
			"messaging.avgTemplate":               "Ø Vorlagen",
			"messaging.conversationsWithMessages": "Konversationen mit Nachrichten",
			"messaging.conversationsWithTemplate": "Konversationen mit Vorlage",
			"messaging.templateMessages":          "Vorlagennachrichten",
			"no":                                  "Nein",
			"noDepartment":                        "Ohne Abteilung",
			"noFunnel":                            "Ohne Funnel",
			"occupancy.agentsSampled":             "Erfasste Mitarbeiter",
			"occupancy.avgOccupancyPct":           "Ø Auslastung (%)",
			"occupancy.teamIdlePct":               "Team-Leerlauf (%)",
			"occupancy.teamOccupancyPct":          "Team-Auslastung (%)",
			"preparing":                           "Wird erstellt…",
			"presence.offline":                    "Offline",
			"presence.on_call":                    "Im Gespräch",
			"presence.online":                     "Online",
			"queue.abandonRate":                   "Abbruchquote (%)",
			"queue.abandoned":                     "Abgebrochen",
			"queue.avgAsaMins":                    "Ø Antwortzeit in Warteschlange (Min.)",
			"queue.cancelled":                     "Storniert",
			"queue.connected":                     "Verbunden",
			"queue.enqueued":                      "In Warteschlange",
			"queue.overflow":                      "Überlauf",
			"queue.queueFull":                     "Warteschlange voll",
			"queued":                              "In der Warteschlange",
			"ready":                               "Bericht fertig, der Download hat begonnen",
			"reopen.finishedCount":                "Abgeschlossen",
			"reopen.reopenRate":                   "Wiedereröffnungsquote (%)",
			"reopen.reopenedCount":                "Wiedereröffnet",
			"running":                             "Wird erstellt",
			"sections.ai":                         "KI-Bearbeitung",
			"sections.backlogXray":                "Backlog-Röntgenbild",
			"sections.channels":                   "Kanalverteilung",
			"sections.definitions":                "Definitionen der Kennzahlen",
			"sections.departments":                "Nach Abteilung",
			"sections.filters":                    "Angewendete Filter",
			"sections.finishedBySource":           "Art des Abschlusses",
			"sections.frt":                        "Erste Antwort",
			"sections.hourly":                     "Konversationen pro Stunde",
			"sections.kpis":                       "Kennzahlen",
			"sections.members":                    "Nach Mitarbeiter",
			"sections.messaging":                  "Nachrichten pro Konversation",
			"sections.occupancy":                  "Auslastung",
			"sections.period":                     "Zeitraum",
			"sections.projections":                "Prognosen und Ziele",
			"sections.quality":                    "Ergebnisqualität",
			"sections.queue":                      "Warteschlange",
			"sections.reachability":               "Erreichbarkeit pro Kanal",
			"sections.reopen":                     "Wiedereröffnungen",
			"sections.revenue":                    "Umsatz",
			"sections.rework":                     "Nacharbeit",
			"sections.stages":                     "Nach Funnel-Phase",
			"sections.stagesTotals":               "Phasenabdeckung",
			"sections.status":                     "Status der Konversationen",
			"sections.teamRanking":                "Team-Ranking",
			"sections.trend":                      "Trend",
			"stages.stagedEngaged":                "Konversationen in Phasen",
			"stages.stagedShell":                  "Ohne Nachricht, in Phasen",
			"stages.stuck":                        "Festgefahrene Konversationen",
			"stages.unstagedEngaged":              "Konversationen ohne Phase",
			"stages.unstagedShell":                "Ohne Nachricht und ohne Phase",
			"status.finished":                     "Abgeschlossen",
			"status.ongoing":                      "Laufend",
			"status.pending":                      "Wartend",
			"title":                               "Servicebericht",
			"yes":                                 "Ja",
		},
	})
	return labels
}
