package webchat

import "errors"

var (
	ErrOriginInvalid  = errors.New("webchat: allowed site must be an origin such as https://www.example.com")
	ErrOriginInsecure = errors.New("webchat: allowed site must use https (http is accepted only for localhost)")

	ErrWorkspaceIDRequired     = errors.New("webchat: workspace id is required")
	ErrWidgetNameRequired      = errors.New("webchat: widget name is required")
	ErrWidgetNameTooLong       = errors.New("webchat: widget name is too long")
	ErrWidgetOriginsRequired   = errors.New("webchat: at least one allowed site is required")
	ErrWidgetTooManyOrigins    = errors.New("webchat: too many allowed sites")
	ErrWidgetStatusInvalid     = errors.New("webchat: widget status is invalid")
	ErrWidgetPositionInvalid   = errors.New("webchat: widget position is invalid")
	ErrWidgetColorInvalid      = errors.New("webchat: accent colour must be a hex colour such as #1F6FEB")
	ErrWidgetTextTooLong       = errors.New("webchat: widget text is too long")
	ErrIntakeRuleInvalid       = errors.New("webchat: intake field rule is invalid")
	ErrIdentityModeInvalid     = errors.New("webchat: identity mode is invalid")
	ErrPrivacyPolicyURLInvalid = errors.New("webchat: privacy policy must be an https address")
	ErrCountryCodeInvalid      = errors.New("webchat: default country code must have 1 to 3 digits")
	ErrIdentitySecretMissing   = errors.New("webchat: identity verification needs a secret")
	ErrWidgetPublicKeyMissing  = errors.New("webchat: widget public key is missing")
	ErrWidgetNotFound          = errors.New("webchat: widget not found")
	ErrWidgetPaused            = errors.New("webchat: widget is paused")
	ErrVisitorNotFound         = errors.New("webchat: visitor not found")
	ErrVisitorBlocked          = errors.New("webchat: visitor is blocked")
	ErrConversationNotFound    = errors.New("webchat: conversation not found")
	ErrOriginNotAllowed        = errors.New("webchat: this site is not allowed to use the widget")
	ErrIntakeFieldRequired     = errors.New("webchat: a required field is missing")
	ErrIntakeNameInvalid       = errors.New("webchat: name is invalid")
	ErrIntakeEmailInvalid      = errors.New("webchat: email is invalid")
	ErrIntakePhoneInvalid      = errors.New("webchat: phone is invalid")
	ErrIntakeConsentRequired   = errors.New("webchat: consent to the privacy policy is required")
	ErrIntakePending           = errors.New("webchat: the visitor must answer the intake first")
	ErrMessageEmpty            = errors.New("webchat: message is empty")
	ErrMessageTooLong          = errors.New("webchat: message is too long")
	ErrClientMessageIDInvalid  = errors.New("webchat: client message id is invalid")
	ErrSelectionNotOffered     = errors.New("webchat: that option was not offered")
	ErrAttachmentsDisabled     = errors.New("webchat: attachments are disabled on this widget")
	ErrAttachmentTypeRefused   = errors.New("webchat: this file type is not accepted")
	ErrAttachmentTooLarge      = errors.New("webchat: file is too large")
	ErrHumanRequestDisabled    = errors.New("webchat: talking to a person is not offered on this widget")
	ErrVisitorTokenInvalid     = errors.New("webchat: visitor token is not valid")
	ErrVisitorTokenExpired     = errors.New("webchat: visitor token has expired")
	ErrIdentityTokenInvalid    = errors.New("webchat: identity token is not valid")
	ErrIdentityTokenExpired    = errors.New("webchat: identity token has expired")
	ErrIdentityRequired        = errors.New("webchat: this widget only accepts verified visitors")
	ErrChallengeInvalid        = errors.New("webchat: challenge is not valid")
	ErrChallengeExpired        = errors.New("webchat: challenge has expired")
	ErrChallengeUnsolved       = errors.New("webchat: challenge solution is wrong")
	ErrChallengeReused         = errors.New("webchat: challenge was already used")
	ErrSigningKeyMissing       = errors.New("webchat: signing key is not configured")
	ErrRateLimited             = errors.New("webchat: too many requests, try again shortly")
	ErrReferenceNotInWorkspace = errors.New("webchat: the selected agent, workflow, funnel or department is not in this workspace")
)
